/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.texttoaudio;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.CambApiApiException;
import core.CambApiException;
import core.ClientOptions;
import core.MediaTypes;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import core.ResponseBodyInputStream;
import errors.UnprocessableEntityError;
import java.io.IOException;
import java.io.InputStream;
import java.lang.Exception;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;
import resources.texttoaudio.requests.CreateTextToAudioRequestPayload;
import resources.texttoaudio.requests.GetTextToAudioResultTextToSoundResultRunIdGetRequest;
import resources.texttoaudio.requests.GetTextToAudioStatusTextToSoundTaskIdGetRequest;
import resources.texttoaudio.requests.GetTextToSoundResultsTextToSoundResultsPostRequest;
import types.HttpValidationError;
import types.OrchestratorPipelineCallResult;
import types.OrchestratorPipelineResult;
import types.TextToAudioResult;

public class AsyncTextToAudioClient {
  protected final ClientOptions clientOptions;

  public AsyncTextToAudioClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public CompletableFuture<OrchestratorPipelineCallResult> createTextToAudio(
      CreateTextToAudioRequestPayload request) {
    return createTextToAudio(request,null);
  }

  public CompletableFuture<OrchestratorPipelineCallResult> createTextToAudio(
      CreateTextToAudioRequestPayload request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("text-to-sound");if (request.getRunId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
      }
      Map<String, Object> properties = new HashMap<>();
      if (request.getProjectName().isPresent()) {
        properties.put("project_name", request.getProjectName());
      }
      if (request.getProjectDescription().isPresent()) {
        properties.put("project_description", request.getProjectDescription());
      }
      if (request.getFolderId().isPresent()) {
        properties.put("folder_id", request.getFolderId());
      }
      properties.put("prompt", request.getPrompt());
      if (request.getDuration().isPresent()) {
        properties.put("duration", request.getDuration());
      }
      if (request.getAudioType().isPresent()) {
        properties.put("audio_type", request.getAudioType());
      }
      RequestBody body;
      try {
        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(properties), MediaTypes.APPLICATION_JSON);
      }
      catch(Exception e) {
        throw new RuntimeException(e);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json");
      if (request.getTraceparent().isPresent()) {
        _requestBuilder.addHeader("traceparent", request.getTraceparent().get());
      }
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<OrchestratorPipelineCallResult> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineCallResult.class));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 422) {
                future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    public CompletableFuture<OrchestratorPipelineResult> getTextToAudioStatus(String taskId) {
      return getTextToAudioStatus(taskId,GetTextToAudioStatusTextToSoundTaskIdGetRequest.builder().build());
    }

    public CompletableFuture<OrchestratorPipelineResult> getTextToAudioStatus(String taskId,
        GetTextToAudioStatusTextToSoundTaskIdGetRequest request) {
      return getTextToAudioStatus(taskId,request,null);
    }

    public CompletableFuture<OrchestratorPipelineResult> getTextToAudioStatus(String taskId,
        GetTextToAudioStatusTextToSoundTaskIdGetRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("text-to-sound")
        .addPathSegment(taskId);if (request.getRunId().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<OrchestratorPipelineResult> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (response.isSuccessful()) {
                future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineResult.class));
                return;
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              try {
                if (response.code() == 422) {
                  future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      /**
       * Retrieve the Text-to-Audio (TTA) result for a given run.
       * <p>This endpoint validates the provided run ID and retrieves the associated
       * Text-to-Audio output. It supports two output formats:</p>
       * <ul>
       * <li>RAW_BYTES: Streams the audio file in WAV format.</li>
       * <li>FILE_URL: Returns a pre-signed URL for downloading the audio file.</li>
       * </ul>
       * <p>The endpoint ensures that the run type is valid for Text-to-Audio processing
       * and that the storage preferences are applied accordingly.</p>
       * <p>Args:
       * run_id (int): Unique identifier for the TTA run.
       * traceparent (Optional[str]): Trace header for distributed tracing.
       * api_key_obj (dict): API key object containing authentication and storage preferences.
       * output_type (OutputType): Desired output format. Defaults to RAW_BYTES.</p>
       * <p>Returns:
       * StreamingResponse | GetTTAOut:
       * - StreamingResponse: If output_type is RAW_BYTES, a streaming response with the audio in WAV format.
       * - GetTTAOut: If output_type is FILE_URL, a pre-signed URL to access the audio file.</p>
       * <p>Raises:
       * HTTPException:
       * - 400 BAD REQUEST: If the run type is invalid for a TTA run.
       * - 500 INTERNAL SERVER ERROR: If the audio file cannot be fetched or streamed.</p>
       */
      public CompletableFuture<InputStream> getTextToAudioResult(Optional<Integer> runId) {
        return getTextToAudioResult(runId,GetTextToAudioResultTextToSoundResultRunIdGetRequest.builder().build());
      }

      /**
       * Retrieve the Text-to-Audio (TTA) result for a given run.
       * <p>This endpoint validates the provided run ID and retrieves the associated
       * Text-to-Audio output. It supports two output formats:</p>
       * <ul>
       * <li>RAW_BYTES: Streams the audio file in WAV format.</li>
       * <li>FILE_URL: Returns a pre-signed URL for downloading the audio file.</li>
       * </ul>
       * <p>The endpoint ensures that the run type is valid for Text-to-Audio processing
       * and that the storage preferences are applied accordingly.</p>
       * <p>Args:
       * run_id (int): Unique identifier for the TTA run.
       * traceparent (Optional[str]): Trace header for distributed tracing.
       * api_key_obj (dict): API key object containing authentication and storage preferences.
       * output_type (OutputType): Desired output format. Defaults to RAW_BYTES.</p>
       * <p>Returns:
       * StreamingResponse | GetTTAOut:
       * - StreamingResponse: If output_type is RAW_BYTES, a streaming response with the audio in WAV format.
       * - GetTTAOut: If output_type is FILE_URL, a pre-signed URL to access the audio file.</p>
       * <p>Raises:
       * HTTPException:
       * - 400 BAD REQUEST: If the run type is invalid for a TTA run.
       * - 500 INTERNAL SERVER ERROR: If the audio file cannot be fetched or streamed.</p>
       */
      public CompletableFuture<InputStream> getTextToAudioResult(Optional<Integer> runId,
          GetTextToAudioResultTextToSoundResultRunIdGetRequest request) {
        return getTextToAudioResult(runId,request,null);
      }

      /**
       * Retrieve the Text-to-Audio (TTA) result for a given run.
       * <p>This endpoint validates the provided run ID and retrieves the associated
       * Text-to-Audio output. It supports two output formats:</p>
       * <ul>
       * <li>RAW_BYTES: Streams the audio file in WAV format.</li>
       * <li>FILE_URL: Returns a pre-signed URL for downloading the audio file.</li>
       * </ul>
       * <p>The endpoint ensures that the run type is valid for Text-to-Audio processing
       * and that the storage preferences are applied accordingly.</p>
       * <p>Args:
       * run_id (int): Unique identifier for the TTA run.
       * traceparent (Optional[str]): Trace header for distributed tracing.
       * api_key_obj (dict): API key object containing authentication and storage preferences.
       * output_type (OutputType): Desired output format. Defaults to RAW_BYTES.</p>
       * <p>Returns:
       * StreamingResponse | GetTTAOut:
       * - StreamingResponse: If output_type is RAW_BYTES, a streaming response with the audio in WAV format.
       * - GetTTAOut: If output_type is FILE_URL, a pre-signed URL to access the audio file.</p>
       * <p>Raises:
       * HTTPException:
       * - 400 BAD REQUEST: If the run type is invalid for a TTA run.
       * - 500 INTERNAL SERVER ERROR: If the audio file cannot be fetched or streamed.</p>
       */
      public CompletableFuture<InputStream> getTextToAudioResult(Optional<Integer> runId,
          GetTextToAudioResultTextToSoundResultRunIdGetRequest request,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("text-to-sound-result");
          if (runId.isPresent()) {
            httpUrl.addPathSegment(runId.get().toString());
          }
          if (request.getOutputType().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "output_type", request.getOutputType().get(), false);
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<InputStream> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try {
                ResponseBody responseBody = response.body();
                if (response.isSuccessful()) {
                  future.complete(new ResponseBodyInputStream(response));
                  return;
                }
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        public CompletableFuture<Map<String, TextToAudioResult>> getTextToSoundResults(
            GetTextToSoundResultsTextToSoundResultsPostRequest request) {
          return getTextToSoundResults(request,null);
        }

        public CompletableFuture<Map<String, TextToAudioResult>> getTextToSoundResults(
            GetTextToSoundResultsTextToSoundResultsPostRequest request,
            RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("text-to-sound-results");if (request.getRunId().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
            }
            RequestBody body;
            try {
              body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
            }
            catch(Exception e) {
              throw new RuntimeException(e);
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("POST", body)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json")
              .addHeader("Accept", "application/json");
            if (request.getTraceparent().isPresent()) {
              _requestBuilder.addHeader("traceparent", request.getTraceparent().get());
            }
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<Map<String, TextToAudioResult>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  if (response.isSuccessful()) {
                    future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<Map<String, TextToAudioResult>>() {}));
                    return;
                  }
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  try {
                    if (response.code() == 422) {
                      future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                      return;
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
              }
            });
            return future;
          }
        }
