/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.folders.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.Nullable;
import core.NullableNonemptyFilter;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListFoldersFoldersGetRequest.Builder.class
)
public final class ListFoldersFoldersGetRequest {
  private final Optional<Integer> limit;

  private final Optional<String> searchQuery;

  private final Optional<Integer> runId;

  private final Map<String, Object> additionalProperties;

  private ListFoldersFoldersGetRequest(Optional<Integer> limit, Optional<String> searchQuery,
      Optional<Integer> runId, Map<String, Object> additionalProperties) {
    this.limit = limit;
    this.searchQuery = searchQuery;
    this.runId = runId;
    this.additionalProperties = additionalProperties;
  }

  @JsonIgnore
  public Optional<Integer> getLimit() {
    if (limit == null) {
      return Optional.empty();
    }
    return limit;
  }

  @JsonIgnore
  public Optional<String> getSearchQuery() {
    if (searchQuery == null) {
      return Optional.empty();
    }
    return searchQuery;
  }

  @JsonIgnore
  public Optional<Integer> getRunId() {
    if (runId == null) {
      return Optional.empty();
    }
    return runId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("limit")
  private Optional<Integer> _getLimit() {
    return limit;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("search_query")
  private Optional<String> _getSearchQuery() {
    return searchQuery;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("run_id")
  private Optional<Integer> _getRunId() {
    return runId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListFoldersFoldersGetRequest && equalTo((ListFoldersFoldersGetRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListFoldersFoldersGetRequest other) {
    return limit.equals(other.limit) && searchQuery.equals(other.searchQuery) && runId.equals(other.runId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.limit, this.searchQuery, this.runId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Integer> limit = Optional.empty();

    private Optional<String> searchQuery = Optional.empty();

    private Optional<Integer> runId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ListFoldersFoldersGetRequest other) {
      limit(other.getLimit());
      searchQuery(other.getSearchQuery());
      runId(other.getRunId());
      return this;
    }

    @JsonSetter(
        value = "limit",
        nulls = Nulls.SKIP
    )
    public Builder limit(Optional<Integer> limit) {
      this.limit = limit;
      return this;
    }

    public Builder limit(Integer limit) {
      this.limit = Optional.ofNullable(limit);
      return this;
    }

    public Builder limit(Nullable<Integer> limit) {
      if (limit.isNull()) {
        this.limit = null;
      }
      else if (limit.isEmpty()) {
        this.limit = Optional.empty();
      }
      else {
        this.limit = Optional.of(limit.get());
      }
      return this;
    }

    @JsonSetter(
        value = "search_query",
        nulls = Nulls.SKIP
    )
    public Builder searchQuery(Optional<String> searchQuery) {
      this.searchQuery = searchQuery;
      return this;
    }

    public Builder searchQuery(String searchQuery) {
      this.searchQuery = Optional.ofNullable(searchQuery);
      return this;
    }

    public Builder searchQuery(Nullable<String> searchQuery) {
      if (searchQuery.isNull()) {
        this.searchQuery = null;
      }
      else if (searchQuery.isEmpty()) {
        this.searchQuery = Optional.empty();
      }
      else {
        this.searchQuery = Optional.of(searchQuery.get());
      }
      return this;
    }

    @JsonSetter(
        value = "run_id",
        nulls = Nulls.SKIP
    )
    public Builder runId(Optional<Integer> runId) {
      this.runId = runId;
      return this;
    }

    public Builder runId(Integer runId) {
      this.runId = Optional.ofNullable(runId);
      return this;
    }

    public Builder runId(Nullable<Integer> runId) {
      if (runId.isNull()) {
        this.runId = null;
      }
      else if (runId.isEmpty()) {
        this.runId = Optional.empty();
      }
      else {
        this.runId = Optional.of(runId.get());
      }
      return this;
    }

    public ListFoldersFoldersGetRequest build() {
      return new ListFoldersFoldersGetRequest(limit, searchQuery, runId, additionalProperties);
    }
  }
}
