/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.story;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.CambApiApiException;
import core.CambApiException;
import core.ClientOptions;
import core.MediaTypes;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import errors.UnprocessableEntityError;
import java.io.File;
import java.io.IOException;
import java.lang.Exception;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;
import java.nio.file.Files;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.MediaType;
import okhttp3.MultipartBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;
import resources.story.requests.BodyCreateStoryStoryPost;
import resources.story.requests.BodySetupStoryStorySetupPost;
import resources.story.requests.GetStoriesRunsResultsStoriesResultsPostRequest;
import resources.story.requests.GetStoryRunInfoStoryResultRunIdGetRequest;
import resources.story.requests.GetStoryStatusStoryTaskIdGetRequest;
import resources.story.types.CreateStoryStoryPostResponse;
import resources.story.types.SetupStoryStorySetupPostResponse;
import types.HttpValidationError;
import types.OrchestratorPipelineResult;

public class AsyncStoryClient {
  protected final ClientOptions clientOptions;

  public AsyncStoryClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public CompletableFuture<CreateStoryStoryPostResponse> createStory(File file,
      BodyCreateStoryStoryPost request) {
    return createStory(file,request,null);
  }

  public CompletableFuture<CreateStoryStoryPostResponse> createStory(File file,
      BodyCreateStoryStoryPost request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("story");if (request.getRunId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
      }
      MultipartBody.Builder body = new MultipartBody.Builder().setType(MultipartBody.FORM);
      try {
        String fileMimeType = Files.probeContentType(file.toPath());
        MediaType fileMimeTypeMediaType = fileMimeType != null ? MediaType.parse(fileMimeType) : null;
        body.addFormDataPart("file", file.getName(), RequestBody.create(fileMimeTypeMediaType, file));
        body.addFormDataPart("source_language", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getSourceLanguage()));
        if (request.getTitle().isPresent()) {
          body.addFormDataPart("title", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getTitle().get()));
        }
        if (request.getDescription().isPresent()) {
          body.addFormDataPart("description", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getDescription().get()));
        }
        if (request.getNarratorVoiceId().isPresent()) {
          body.addFormDataPart("narrator_voice_id", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getNarratorVoiceId().get()));
        }
        if (request.getFolderId().isPresent()) {
          body.addFormDataPart("folder_id", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getFolderId().get()));
        }
        if (request.getChosenDictionaries().isPresent()) {
          body.addFormDataPart("chosen_dictionaries", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getChosenDictionaries().get()));
        }
      }
      catch(Exception e) {
        throw new RuntimeException(e);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body.build())
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<CreateStoryStoryPostResponse> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CreateStoryStoryPostResponse.class));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 422) {
                future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    public CompletableFuture<SetupStoryStorySetupPostResponse> setupStory(File file,
        BodySetupStoryStorySetupPost request) {
      return setupStory(file,request,null);
    }

    public CompletableFuture<SetupStoryStorySetupPostResponse> setupStory(File file,
        BodySetupStoryStorySetupPost request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("story-setup");if (request.getRunId().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
        }
        MultipartBody.Builder body = new MultipartBody.Builder().setType(MultipartBody.FORM);
        try {
          String fileMimeType = Files.probeContentType(file.toPath());
          MediaType fileMimeTypeMediaType = fileMimeType != null ? MediaType.parse(fileMimeType) : null;
          body.addFormDataPart("file", file.getName(), RequestBody.create(fileMimeTypeMediaType, file));
          body.addFormDataPart("source_language", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getSourceLanguage()));
          if (request.getTitle().isPresent()) {
            body.addFormDataPart("title", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getTitle().get()));
          }
          if (request.getDescription().isPresent()) {
            body.addFormDataPart("description", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getDescription().get()));
          }
          if (request.getNarratorVoiceId().isPresent()) {
            body.addFormDataPart("narrator_voice_id", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getNarratorVoiceId().get()));
          }
          if (request.getFolderId().isPresent()) {
            body.addFormDataPart("folder_id", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getFolderId().get()));
          }
          if (request.getChosenDictionaries().isPresent()) {
            body.addFormDataPart("chosen_dictionaries", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getChosenDictionaries().get()));
          }
        }
        catch(Exception e) {
          throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("POST", body.build())
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<SetupStoryStorySetupPostResponse> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (response.isSuccessful()) {
                future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), SetupStoryStorySetupPostResponse.class));
                return;
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              try {
                if (response.code() == 422) {
                  future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      public CompletableFuture<OrchestratorPipelineResult> getStoryStatus(String taskId) {
        return getStoryStatus(taskId,GetStoryStatusStoryTaskIdGetRequest.builder().build());
      }

      public CompletableFuture<OrchestratorPipelineResult> getStoryStatus(String taskId,
          GetStoryStatusStoryTaskIdGetRequest request) {
        return getStoryStatus(taskId,request,null);
      }

      public CompletableFuture<OrchestratorPipelineResult> getStoryStatus(String taskId,
          GetStoryStatusStoryTaskIdGetRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("story")
          .addPathSegment(taskId);if (request.getRunId().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<OrchestratorPipelineResult> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                if (response.isSuccessful()) {
                  future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineResult.class));
                  return;
                }
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                try {
                  if (response.code() == 422) {
                    future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                    return;
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        public CompletableFuture<Map<String, Object>> getStoryRunInfo(Optional<Integer> runId) {
          return getStoryRunInfo(runId,GetStoryRunInfoStoryResultRunIdGetRequest.builder().build());
        }

        public CompletableFuture<Map<String, Object>> getStoryRunInfo(Optional<Integer> runId,
            GetStoryRunInfoStoryResultRunIdGetRequest request) {
          return getStoryRunInfo(runId,request,null);
        }

        public CompletableFuture<Map<String, Object>> getStoryRunInfo(Optional<Integer> runId,
            GetStoryRunInfoStoryResultRunIdGetRequest request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("story-result");
            if (runId.isPresent()) {
              httpUrl.addPathSegment(runId.get().toString());
            }
            if (request.getIncludeTranscript().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "include_transcript", request.getIncludeTranscript().get().toString(), false);
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("GET", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json")
              .addHeader("Accept", "application/json");
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<Map<String, Object>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  if (response.isSuccessful()) {
                    future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<Map<String, Object>>() {}));
                    return;
                  }
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  try {
                    if (response.code() == 422) {
                      future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                      return;
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
              }
            });
            return future;
          }

          public CompletableFuture<Map<String, Map<String, Object>>> getStoriesRunsResults(
              GetStoriesRunsResultsStoriesResultsPostRequest request) {
            return getStoriesRunsResults(request,null);
          }

          public CompletableFuture<Map<String, Map<String, Object>>> getStoriesRunsResults(
              GetStoriesRunsResultsStoriesResultsPostRequest request,
              RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("stories-results");if (request.getRunId().isPresent()) {
                QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
              }
              RequestBody body;
              try {
                body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
              }
              catch(Exception e) {
                throw new RuntimeException(e);
              }
              Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
              if (request.getTraceparent().isPresent()) {
                _requestBuilder.addHeader("traceparent", request.getTraceparent().get());
              }
              Request okhttpRequest = _requestBuilder.build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              CompletableFuture<Map<String, Map<String, Object>>> future = new CompletableFuture<>();
              client.newCall(okhttpRequest).enqueue(new Callback() {
                @Override
                public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                  try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                      future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<Map<String, Map<String, Object>>>() {}));
                      return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                      if (response.code() == 422) {
                        future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                        return;
                      }
                    }
                    catch (JsonProcessingException ignored) {
                      // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                    return;
                  }
                  catch (IOException e) {
                    future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                  }
                }

                @Override
                public void onFailure(@NotNull Call call, @NotNull IOException e) {
                  future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                }
              });
              return future;
            }
          }
