/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.dictionaries;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.CambApiApiException;
import core.CambApiException;
import core.ClientOptions;
import core.MediaTypes;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import errors.UnprocessableEntityError;
import java.io.File;
import java.io.IOException;
import java.lang.Exception;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;
import java.nio.file.Files;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.MediaType;
import okhttp3.MultipartBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;
import resources.dictionaries.requests.AddDictionaryTermPayload;
import resources.dictionaries.requests.BodyCreateDictionaryFromFileDictionariesCreateFromFilePost;
import resources.dictionaries.requests.DeleteDictionaryDictionariesDictionaryIdDeleteRequest;
import resources.dictionaries.requests.DeleteDictionaryTermDictionariesTermDictionaryIdTermIdDeleteRequest;
import resources.dictionaries.requests.GetDictionariesDictionariesGetRequest;
import resources.dictionaries.requests.GetDictionaryDetailsDictionariesDictionaryIdFullDetailsGetRequest;
import resources.dictionaries.requests.GetDictionaryInfoDictionariesDictionaryIdGetRequest;
import resources.dictionaries.requests.UpdateTermTranslationsPayload;
import types.DictionaryWithTerms;
import types.HttpValidationError;

public class AsyncDictionariesClient {
  protected final ClientOptions clientOptions;

  public AsyncDictionariesClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public CompletableFuture<List<DictionaryWithTerms>> getDictionaries() {
    return getDictionaries(GetDictionariesDictionariesGetRequest.builder().build());
  }

  public CompletableFuture<List<DictionaryWithTerms>> getDictionaries(
      GetDictionariesDictionariesGetRequest request) {
    return getDictionaries(request,null);
  }

  public CompletableFuture<List<DictionaryWithTerms>> getDictionaries(
      GetDictionariesDictionariesGetRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("dictionaries");if (request.getRunId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<List<DictionaryWithTerms>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<List<DictionaryWithTerms>>() {}));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 422) {
                future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    public CompletableFuture<Object> createDictionaryFromFile(File dictionaryFile,
        BodyCreateDictionaryFromFileDictionariesCreateFromFilePost request) {
      return createDictionaryFromFile(dictionaryFile,request,null);
    }

    public CompletableFuture<Object> createDictionaryFromFile(File dictionaryFile,
        BodyCreateDictionaryFromFileDictionariesCreateFromFilePost request,
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("dictionaries/create-from-file");if (request.getRunId().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
        }
        MultipartBody.Builder body = new MultipartBody.Builder().setType(MultipartBody.FORM);
        try {
          String dictionaryFileMimeType = Files.probeContentType(dictionaryFile.toPath());
          MediaType dictionaryFileMimeTypeMediaType = dictionaryFileMimeType != null ? MediaType.parse(dictionaryFileMimeType) : null;
          body.addFormDataPart("dictionary_file", dictionaryFile.getName(), RequestBody.create(dictionaryFileMimeTypeMediaType, dictionaryFile));
          body.addFormDataPart("dictionary_name", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getDictionaryName()));
          if (request.getDictionaryDescription().isPresent()) {
            body.addFormDataPart("dictionary_description", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getDictionaryDescription().get()));
          }
        }
        catch(Exception e) {
          throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("POST", body.build())
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<Object> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (response.isSuccessful()) {
                future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), Object.class));
                return;
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              try {
                if (response.code() == 422) {
                  future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      public CompletableFuture<DictionaryWithTerms> getDictionaryInfo(int dictionaryId) {
        return getDictionaryInfo(dictionaryId,GetDictionaryInfoDictionariesDictionaryIdGetRequest.builder().build());
      }

      public CompletableFuture<DictionaryWithTerms> getDictionaryInfo(int dictionaryId,
          GetDictionaryInfoDictionariesDictionaryIdGetRequest request) {
        return getDictionaryInfo(dictionaryId,request,null);
      }

      public CompletableFuture<DictionaryWithTerms> getDictionaryInfo(int dictionaryId,
          GetDictionaryInfoDictionariesDictionaryIdGetRequest request,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("dictionaries")
          .addPathSegment(Integer.toString(dictionaryId));if (request.getRunId().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<DictionaryWithTerms> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                if (response.isSuccessful()) {
                  future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), DictionaryWithTerms.class));
                  return;
                }
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                try {
                  if (response.code() == 422) {
                    future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                    return;
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        public CompletableFuture<Object> deleteDictionary(int dictionaryId) {
          return deleteDictionary(dictionaryId,DeleteDictionaryDictionariesDictionaryIdDeleteRequest.builder().build());
        }

        public CompletableFuture<Object> deleteDictionary(int dictionaryId,
            DeleteDictionaryDictionariesDictionaryIdDeleteRequest request) {
          return deleteDictionary(dictionaryId,request,null);
        }

        public CompletableFuture<Object> deleteDictionary(int dictionaryId,
            DeleteDictionaryDictionariesDictionaryIdDeleteRequest request,
            RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("dictionaries")
            .addPathSegment(Integer.toString(dictionaryId));if (request.getRunId().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("DELETE", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json")
              .addHeader("Accept", "application/json");
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<Object> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  if (response.isSuccessful()) {
                    future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), Object.class));
                    return;
                  }
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  try {
                    if (response.code() == 422) {
                      future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                      return;
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
              }
            });
            return future;
          }

          public CompletableFuture<DictionaryWithTerms> getDictionaryDetails(int dictionaryId) {
            return getDictionaryDetails(dictionaryId,GetDictionaryDetailsDictionariesDictionaryIdFullDetailsGetRequest.builder().build());
          }

          public CompletableFuture<DictionaryWithTerms> getDictionaryDetails(int dictionaryId,
              GetDictionaryDetailsDictionariesDictionaryIdFullDetailsGetRequest request) {
            return getDictionaryDetails(dictionaryId,request,null);
          }

          public CompletableFuture<DictionaryWithTerms> getDictionaryDetails(int dictionaryId,
              GetDictionaryDetailsDictionariesDictionaryIdFullDetailsGetRequest request,
              RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("dictionaries")
              .addPathSegment(Integer.toString(dictionaryId))
              .addPathSegments("full-details");if (request.getLimit().isPresent()) {
                QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get().toString(), false);
              }
              if (request.getSearchTerm().isPresent()) {
                QueryStringMapper.addQueryParameter(httpUrl, "search_term", request.getSearchTerm().get(), false);
              }
              if (request.getRunId().isPresent()) {
                QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
              }
              Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
              Request okhttpRequest = _requestBuilder.build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              CompletableFuture<DictionaryWithTerms> future = new CompletableFuture<>();
              client.newCall(okhttpRequest).enqueue(new Callback() {
                @Override
                public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                  try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                      future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), DictionaryWithTerms.class));
                      return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                      if (response.code() == 422) {
                        future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                        return;
                      }
                    }
                    catch (JsonProcessingException ignored) {
                      // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                    return;
                  }
                  catch (IOException e) {
                    future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                  }
                }

                @Override
                public void onFailure(@NotNull Call call, @NotNull IOException e) {
                  future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                }
              });
              return future;
            }

            public CompletableFuture<Object> addTermToDictionary(int dictionaryId,
                AddDictionaryTermPayload request) {
              return addTermToDictionary(dictionaryId,request,null);
            }

            public CompletableFuture<Object> addTermToDictionary(int dictionaryId,
                AddDictionaryTermPayload request, RequestOptions requestOptions) {
              HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                .addPathSegments("dictionaries")
                .addPathSegment(Integer.toString(dictionaryId))
                .addPathSegments("add-term");if (request.getRunId().isPresent()) {
                  QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
                }
                Map<String, Object> properties = new HashMap<>();
                properties.put("translations", request.getTranslations());
                RequestBody body;
                try {
                  body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(properties), MediaTypes.APPLICATION_JSON);
                }
                catch(Exception e) {
                  throw new RuntimeException(e);
                }
                Request.Builder _requestBuilder = new Request.Builder()
                  .url(httpUrl.build())
                  .method("POST", body)
                  .headers(Headers.of(clientOptions.headers(requestOptions)))
                  .addHeader("Content-Type", "application/json")
                  .addHeader("Accept", "application/json");
                Request okhttpRequest = _requestBuilder.build();
                OkHttpClient client = clientOptions.httpClient();
                if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                  client = clientOptions.httpClientWithTimeout(requestOptions);
                }
                CompletableFuture<Object> future = new CompletableFuture<>();
                client.newCall(okhttpRequest).enqueue(new Callback() {
                  @Override
                  public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                    try (ResponseBody responseBody = response.body()) {
                      if (response.isSuccessful()) {
                        future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), Object.class));
                        return;
                      }
                      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                      try {
                        if (response.code() == 422) {
                          future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                          return;
                        }
                      }
                      catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                      }
                      future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                      return;
                    }
                    catch (IOException e) {
                      future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                    }
                  }

                  @Override
                  public void onFailure(@NotNull Call call, @NotNull IOException e) {
                    future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                  }
                });
                return future;
              }

              public CompletableFuture<Object> updateTermTranslationInDictionaryUsingTermId(
                  int dictionaryId, int termId, UpdateTermTranslationsPayload request) {
                return updateTermTranslationInDictionaryUsingTermId(dictionaryId,termId,request,null);
              }

              public CompletableFuture<Object> updateTermTranslationInDictionaryUsingTermId(
                  int dictionaryId, int termId, UpdateTermTranslationsPayload request,
                  RequestOptions requestOptions) {
                HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                  .addPathSegments("dictionaries/term")
                  .addPathSegment(Integer.toString(dictionaryId))
                  .addPathSegment(Integer.toString(termId));if (request.getRunId().isPresent()) {
                    QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
                  }
                  Map<String, Object> properties = new HashMap<>();
                  properties.put("translations", request.getTranslations());
                  RequestBody body;
                  try {
                    body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(properties), MediaTypes.APPLICATION_JSON);
                  }
                  catch(Exception e) {
                    throw new RuntimeException(e);
                  }
                  Request.Builder _requestBuilder = new Request.Builder()
                    .url(httpUrl.build())
                    .method("PUT", body)
                    .headers(Headers.of(clientOptions.headers(requestOptions)))
                    .addHeader("Content-Type", "application/json")
                    .addHeader("Accept", "application/json");
                  Request okhttpRequest = _requestBuilder.build();
                  OkHttpClient client = clientOptions.httpClient();
                  if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                    client = clientOptions.httpClientWithTimeout(requestOptions);
                  }
                  CompletableFuture<Object> future = new CompletableFuture<>();
                  client.newCall(okhttpRequest).enqueue(new Callback() {
                    @Override
                    public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                      try (ResponseBody responseBody = response.body()) {
                        if (response.isSuccessful()) {
                          future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), Object.class));
                          return;
                        }
                        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                        try {
                          if (response.code() == 422) {
                            future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                            return;
                          }
                        }
                        catch (JsonProcessingException ignored) {
                          // unable to map error response, throwing generic error
                        }
                        future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                        return;
                      }
                      catch (IOException e) {
                        future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                      }
                    }

                    @Override
                    public void onFailure(@NotNull Call call, @NotNull IOException e) {
                      future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                    }
                  });
                  return future;
                }

                public CompletableFuture<Object> deleteDictionaryTerm(int dictionaryId,
                    int termId) {
                  return deleteDictionaryTerm(dictionaryId,termId,DeleteDictionaryTermDictionariesTermDictionaryIdTermIdDeleteRequest.builder().build());
                }

                public CompletableFuture<Object> deleteDictionaryTerm(int dictionaryId, int termId,
                    DeleteDictionaryTermDictionariesTermDictionaryIdTermIdDeleteRequest request) {
                  return deleteDictionaryTerm(dictionaryId,termId,request,null);
                }

                public CompletableFuture<Object> deleteDictionaryTerm(int dictionaryId, int termId,
                    DeleteDictionaryTermDictionariesTermDictionaryIdTermIdDeleteRequest request,
                    RequestOptions requestOptions) {
                  HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                    .addPathSegments("dictionaries/term")
                    .addPathSegment(Integer.toString(dictionaryId))
                    .addPathSegment(Integer.toString(termId));if (request.getRunId().isPresent()) {
                      QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
                    }
                    Request.Builder _requestBuilder = new Request.Builder()
                      .url(httpUrl.build())
                      .method("DELETE", null)
                      .headers(Headers.of(clientOptions.headers(requestOptions)))
                      .addHeader("Content-Type", "application/json")
                      .addHeader("Accept", "application/json");
                    Request okhttpRequest = _requestBuilder.build();
                    OkHttpClient client = clientOptions.httpClient();
                    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                      client = clientOptions.httpClientWithTimeout(requestOptions);
                    }
                    CompletableFuture<Object> future = new CompletableFuture<>();
                    client.newCall(okhttpRequest).enqueue(new Callback() {
                      @Override
                      public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                        try (ResponseBody responseBody = response.body()) {
                          if (response.isSuccessful()) {
                            future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), Object.class));
                            return;
                          }
                          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                          try {
                            if (response.code() == 422) {
                              future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                              return;
                            }
                          }
                          catch (JsonProcessingException ignored) {
                            // unable to map error response, throwing generic error
                          }
                          future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                          return;
                        }
                        catch (IOException e) {
                          future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                        }
                      }

                      @Override
                      public void onFailure(@NotNull Call call, @NotNull IOException e) {
                        future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                      }
                    });
                    return future;
                  }
                }
