/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.texttospeech.types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum SpeechModel {
  AUTO("auto"),

  MARS8("mars-8"),

  MARS8FLASH("mars-8-flash"),

  MARS8INSTRUCT("mars-8-instruct"),

  MARS7("mars-7"),

  MARS6("mars-6"),

  MARSPRO("mars-pro"),

  MARSFLASH("mars-flash"),

  MARSINSTRUCT("mars-instruct"),

  MARS_PRO("mars-pro"),

  MARS_FLASH("mars-flash"),

  MARS_INSTRUCT("mars-instruct");

  private final String value;

  SpeechModel(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
