/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.story.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.Nullable;
import core.NullableNonemptyFilter;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BodyCreateStoryStoryPost.Builder.class
)
public final class BodyCreateStoryStoryPost {
  private final Optional<Integer> runId;

  private final int sourceLanguage;

  private final Optional<String> title;

  private final Optional<String> description;

  private final Optional<Integer> narratorVoiceId;

  private final Optional<Integer> folderId;

  private final Optional<List<Integer>> chosenDictionaries;

  private final Map<String, Object> additionalProperties;

  private BodyCreateStoryStoryPost(Optional<Integer> runId, int sourceLanguage,
      Optional<String> title, Optional<String> description, Optional<Integer> narratorVoiceId,
      Optional<Integer> folderId, Optional<List<Integer>> chosenDictionaries,
      Map<String, Object> additionalProperties) {
    this.runId = runId;
    this.sourceLanguage = sourceLanguage;
    this.title = title;
    this.description = description;
    this.narratorVoiceId = narratorVoiceId;
    this.folderId = folderId;
    this.chosenDictionaries = chosenDictionaries;
    this.additionalProperties = additionalProperties;
  }

  @JsonIgnore
  public Optional<Integer> getRunId() {
    if (runId == null) {
      return Optional.empty();
    }
    return runId;
  }

  @JsonProperty("source_language")
  public int getSourceLanguage() {
    return sourceLanguage;
  }

  @JsonIgnore
  public Optional<String> getTitle() {
    if (title == null) {
      return Optional.empty();
    }
    return title;
  }

  @JsonIgnore
  public Optional<String> getDescription() {
    if (description == null) {
      return Optional.empty();
    }
    return description;
  }

  @JsonIgnore
  public Optional<Integer> getNarratorVoiceId() {
    if (narratorVoiceId == null) {
      return Optional.empty();
    }
    return narratorVoiceId;
  }

  @JsonIgnore
  public Optional<Integer> getFolderId() {
    if (folderId == null) {
      return Optional.empty();
    }
    return folderId;
  }

  @JsonIgnore
  public Optional<List<Integer>> getChosenDictionaries() {
    if (chosenDictionaries == null) {
      return Optional.empty();
    }
    return chosenDictionaries;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("run_id")
  private Optional<Integer> _getRunId() {
    return runId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("title")
  private Optional<String> _getTitle() {
    return title;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("description")
  private Optional<String> _getDescription() {
    return description;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("narrator_voice_id")
  private Optional<Integer> _getNarratorVoiceId() {
    return narratorVoiceId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("folder_id")
  private Optional<Integer> _getFolderId() {
    return folderId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("chosen_dictionaries")
  private Optional<List<Integer>> _getChosenDictionaries() {
    return chosenDictionaries;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BodyCreateStoryStoryPost && equalTo((BodyCreateStoryStoryPost) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BodyCreateStoryStoryPost other) {
    return runId.equals(other.runId) && sourceLanguage == other.sourceLanguage && title.equals(other.title) && description.equals(other.description) && narratorVoiceId.equals(other.narratorVoiceId) && folderId.equals(other.folderId) && chosenDictionaries.equals(other.chosenDictionaries);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.runId, this.sourceLanguage, this.title, this.description, this.narratorVoiceId, this.folderId, this.chosenDictionaries);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static SourceLanguageStage builder() {
    return new Builder();
  }

  public interface SourceLanguageStage {
    _FinalStage sourceLanguage(int sourceLanguage);

    Builder from(BodyCreateStoryStoryPost other);
  }

  public interface _FinalStage {
    BodyCreateStoryStoryPost build();

    _FinalStage runId(Optional<Integer> runId);

    _FinalStage runId(Integer runId);

    _FinalStage runId(Nullable<Integer> runId);

    _FinalStage title(Optional<String> title);

    _FinalStage title(String title);

    _FinalStage title(Nullable<String> title);

    _FinalStage description(Optional<String> description);

    _FinalStage description(String description);

    _FinalStage description(Nullable<String> description);

    _FinalStage narratorVoiceId(Optional<Integer> narratorVoiceId);

    _FinalStage narratorVoiceId(Integer narratorVoiceId);

    _FinalStage narratorVoiceId(Nullable<Integer> narratorVoiceId);

    _FinalStage folderId(Optional<Integer> folderId);

    _FinalStage folderId(Integer folderId);

    _FinalStage folderId(Nullable<Integer> folderId);

    _FinalStage chosenDictionaries(Optional<List<Integer>> chosenDictionaries);

    _FinalStage chosenDictionaries(List<Integer> chosenDictionaries);

    _FinalStage chosenDictionaries(Nullable<List<Integer>> chosenDictionaries);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements SourceLanguageStage, _FinalStage {
    private int sourceLanguage;

    private Optional<List<Integer>> chosenDictionaries = Optional.empty();

    private Optional<Integer> folderId = Optional.empty();

    private Optional<Integer> narratorVoiceId = Optional.empty();

    private Optional<String> description = Optional.empty();

    private Optional<String> title = Optional.empty();

    private Optional<Integer> runId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BodyCreateStoryStoryPost other) {
      runId(other.getRunId());
      sourceLanguage(other.getSourceLanguage());
      title(other.getTitle());
      description(other.getDescription());
      narratorVoiceId(other.getNarratorVoiceId());
      folderId(other.getFolderId());
      chosenDictionaries(other.getChosenDictionaries());
      return this;
    }

    @java.lang.Override
    @JsonSetter("source_language")
    public _FinalStage sourceLanguage(int sourceLanguage) {
      this.sourceLanguage = sourceLanguage;
      return this;
    }

    @java.lang.Override
    public _FinalStage chosenDictionaries(Nullable<List<Integer>> chosenDictionaries) {
      if (chosenDictionaries.isNull()) {
        this.chosenDictionaries = null;
      }
      else if (chosenDictionaries.isEmpty()) {
        this.chosenDictionaries = Optional.empty();
      }
      else {
        this.chosenDictionaries = Optional.of(chosenDictionaries.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage chosenDictionaries(List<Integer> chosenDictionaries) {
      this.chosenDictionaries = Optional.ofNullable(chosenDictionaries);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "chosen_dictionaries",
        nulls = Nulls.SKIP
    )
    public _FinalStage chosenDictionaries(Optional<List<Integer>> chosenDictionaries) {
      this.chosenDictionaries = chosenDictionaries;
      return this;
    }

    @java.lang.Override
    public _FinalStage folderId(Nullable<Integer> folderId) {
      if (folderId.isNull()) {
        this.folderId = null;
      }
      else if (folderId.isEmpty()) {
        this.folderId = Optional.empty();
      }
      else {
        this.folderId = Optional.of(folderId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage folderId(Integer folderId) {
      this.folderId = Optional.ofNullable(folderId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "folder_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage folderId(Optional<Integer> folderId) {
      this.folderId = folderId;
      return this;
    }

    @java.lang.Override
    public _FinalStage narratorVoiceId(Nullable<Integer> narratorVoiceId) {
      if (narratorVoiceId.isNull()) {
        this.narratorVoiceId = null;
      }
      else if (narratorVoiceId.isEmpty()) {
        this.narratorVoiceId = Optional.empty();
      }
      else {
        this.narratorVoiceId = Optional.of(narratorVoiceId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage narratorVoiceId(Integer narratorVoiceId) {
      this.narratorVoiceId = Optional.ofNullable(narratorVoiceId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "narrator_voice_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage narratorVoiceId(Optional<Integer> narratorVoiceId) {
      this.narratorVoiceId = narratorVoiceId;
      return this;
    }

    @java.lang.Override
    public _FinalStage description(Nullable<String> description) {
      if (description.isNull()) {
        this.description = null;
      }
      else if (description.isEmpty()) {
        this.description = Optional.empty();
      }
      else {
        this.description = Optional.of(description.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public _FinalStage description(Optional<String> description) {
      this.description = description;
      return this;
    }

    @java.lang.Override
    public _FinalStage title(Nullable<String> title) {
      if (title.isNull()) {
        this.title = null;
      }
      else if (title.isEmpty()) {
        this.title = Optional.empty();
      }
      else {
        this.title = Optional.of(title.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage title(String title) {
      this.title = Optional.ofNullable(title);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "title",
        nulls = Nulls.SKIP
    )
    public _FinalStage title(Optional<String> title) {
      this.title = title;
      return this;
    }

    @java.lang.Override
    public _FinalStage runId(Nullable<Integer> runId) {
      if (runId.isNull()) {
        this.runId = null;
      }
      else if (runId.isEmpty()) {
        this.runId = Optional.empty();
      }
      else {
        this.runId = Optional.of(runId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage runId(Integer runId) {
      this.runId = Optional.ofNullable(runId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "run_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage runId(Optional<Integer> runId) {
      this.runId = runId;
      return this;
    }

    @java.lang.Override
    public BodyCreateStoryStoryPost build() {
      return new BodyCreateStoryStoryPost(runId, sourceLanguage, title, description, narratorVoiceId, folderId, chosenDictionaries, additionalProperties);
    }
  }
}
