/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.translation;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.CambApiApiException;
import core.CambApiException;
import core.ClientOptions;
import core.MediaTypes;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import errors.UnprocessableEntityError;
import java.io.IOException;
import java.lang.Exception;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;
import resources.translation.requests.CreateTranslationRequestPayload;
import resources.translation.requests.CreateTranslationStreamRequestPayload;
import resources.translation.requests.GetTranslationResultTranslationResultRunIdGetRequest;
import resources.translation.requests.GetTranslationResultsTranslationResultsPostRequest;
import resources.translation.requests.GetTranslationTaskStatusTranslateTaskIdGetRequest;
import types.HttpValidationError;
import types.OrchestratorPipelineResult;
import types.TranslationResult;

public class AsyncTranslationClient {
  protected final ClientOptions clientOptions;

  public AsyncTranslationClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public CompletableFuture<Object> translationStream(
      CreateTranslationStreamRequestPayload request) {
    return translationStream(request,null);
  }

  public CompletableFuture<Object> translationStream(CreateTranslationStreamRequestPayload request,
      RequestOptions requestOptions) {
    HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("translation/stream")
      .build();
    Map<String, Object> properties = new HashMap<>();
    properties.put("source_language", request.getSourceLanguage());
    properties.put("target_language", request.getTargetLanguage());
    properties.put("text", request.getText());
    if (request.getFormality().isPresent()) {
      properties.put("formality", request.getFormality());
    }
    if (request.getGender().isPresent()) {
      properties.put("gender", request.getGender());
    }
    if (request.getTeamId().isPresent()) {
      properties.put("team_id", request.getTeamId());
    }
    if (request.getProjectName().isPresent()) {
      properties.put("project_name", request.getProjectName());
    }
    if (request.getProjectDescription().isPresent()) {
      properties.put("project_description", request.getProjectDescription());
    }
    if (request.getFolderId().isPresent()) {
      properties.put("folder_id", request.getFolderId());
    }
    RequestBody body;
    try {
      body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(properties), MediaTypes.APPLICATION_JSON);
    }
    catch(Exception e) {
      throw new RuntimeException(e);
    }
    Request.Builder _requestBuilder = new Request.Builder()
      .url(httpUrl)
      .method("POST", body)
      .headers(Headers.of(clientOptions.headers(requestOptions)))
      .addHeader("Content-Type", "application/json")
      .addHeader("Accept", "application/json");
    if (request.getTraceparent().isPresent()) {
      _requestBuilder.addHeader("traceparent", request.getTraceparent().get());
    }
    Request okhttpRequest = _requestBuilder.build();
    OkHttpClient client = clientOptions.httpClient();
    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
      client = clientOptions.httpClientWithTimeout(requestOptions);
    }
    CompletableFuture<Object> future = new CompletableFuture<>();
    client.newCall(okhttpRequest).enqueue(new Callback() {
      @Override
      public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
        try (ResponseBody responseBody = response.body()) {
          if (response.isSuccessful()) {
            future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), Object.class));
            return;
          }
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          try {
            if (response.code() == 422) {
              future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
              return;
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
          return;
        }
        catch (IOException e) {
          future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
        }
      }

      @Override
      public void onFailure(@NotNull Call call, @NotNull IOException e) {
        future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
      }
    });
    return future;
  }

  public CompletableFuture<Object> createTranslation(CreateTranslationRequestPayload request) {
    return createTranslation(request,null);
  }

  public CompletableFuture<Object> createTranslation(CreateTranslationRequestPayload request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("translate");if (request.getRunId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
      }
      Map<String, Object> properties = new HashMap<>();
      if (request.getProjectName().isPresent()) {
        properties.put("project_name", request.getProjectName());
      }
      if (request.getProjectDescription().isPresent()) {
        properties.put("project_description", request.getProjectDescription());
      }
      if (request.getFolderId().isPresent()) {
        properties.put("folder_id", request.getFolderId());
      }
      properties.put("texts", request.getTexts());
      if (request.getAge().isPresent()) {
        properties.put("age", request.getAge());
      }
      if (request.getFormality().isPresent()) {
        properties.put("formality", request.getFormality());
      }
      if (request.getGender().isPresent()) {
        properties.put("gender", request.getGender());
      }
      properties.put("source_language", request.getSourceLanguage());
      properties.put("target_language", request.getTargetLanguage());
      if (request.getChosenDictionaries().isPresent()) {
        properties.put("chosen_dictionaries", request.getChosenDictionaries());
      }
      RequestBody body;
      try {
        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(properties), MediaTypes.APPLICATION_JSON);
      }
      catch(Exception e) {
        throw new RuntimeException(e);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<Object> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), Object.class));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 422) {
                future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    public CompletableFuture<OrchestratorPipelineResult> getTranslationTaskStatus(String taskId) {
      return getTranslationTaskStatus(taskId,GetTranslationTaskStatusTranslateTaskIdGetRequest.builder().build());
    }

    public CompletableFuture<OrchestratorPipelineResult> getTranslationTaskStatus(String taskId,
        GetTranslationTaskStatusTranslateTaskIdGetRequest request) {
      return getTranslationTaskStatus(taskId,request,null);
    }

    public CompletableFuture<OrchestratorPipelineResult> getTranslationTaskStatus(String taskId,
        GetTranslationTaskStatusTranslateTaskIdGetRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("translate")
        .addPathSegment(taskId);if (request.getRunId().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<OrchestratorPipelineResult> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (response.isSuccessful()) {
                future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineResult.class));
                return;
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              try {
                if (response.code() == 422) {
                  future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      /**
       * NOTE: This endpoint should be called only by the users to get values for their runs via API.
       * Further we need to validate if the user has access to the run_id, otherwise we should not return the output urls.
       */
      public CompletableFuture<TranslationResult> getTranslationResult(Optional<Integer> runId) {
        return getTranslationResult(runId,GetTranslationResultTranslationResultRunIdGetRequest.builder().build());
      }

      /**
       * NOTE: This endpoint should be called only by the users to get values for their runs via API.
       * Further we need to validate if the user has access to the run_id, otherwise we should not return the output urls.
       */
      public CompletableFuture<TranslationResult> getTranslationResult(Optional<Integer> runId,
          GetTranslationResultTranslationResultRunIdGetRequest request) {
        return getTranslationResult(runId,request,null);
      }

      /**
       * NOTE: This endpoint should be called only by the users to get values for their runs via API.
       * Further we need to validate if the user has access to the run_id, otherwise we should not return the output urls.
       */
      public CompletableFuture<TranslationResult> getTranslationResult(Optional<Integer> runId,
          GetTranslationResultTranslationResultRunIdGetRequest request,
          RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("translation-result");
          if (runId.isPresent()) {
            httpUrl.addPathSegment(runId.get().toString());
          }

          .build();
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl)
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json");
        if (request.getTraceparent().isPresent()) {
          _requestBuilder.addHeader("traceparent", request.getTraceparent().get());
        }
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<TranslationResult> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (response.isSuccessful()) {
                future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), TranslationResult.class));
                return;
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              try {
                if (response.code() == 422) {
                  future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      public CompletableFuture<Map<String, TranslationResult>> getTranslationResults(
          GetTranslationResultsTranslationResultsPostRequest request) {
        return getTranslationResults(request,null);
      }

      public CompletableFuture<Map<String, TranslationResult>> getTranslationResults(
          GetTranslationResultsTranslationResultsPostRequest request,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("translation-results");if (request.getRunId().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
          }
          RequestBody body;
          try {
            body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
          }
          catch(Exception e) {
            throw new RuntimeException(e);
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("POST", body)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json");
          if (request.getTraceparent().isPresent()) {
            _requestBuilder.addHeader("traceparent", request.getTraceparent().get());
          }
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<Map<String, TranslationResult>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                if (response.isSuccessful()) {
                  future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<Map<String, TranslationResult>>() {}));
                  return;
                }
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                try {
                  if (response.code() == 422) {
                    future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                    return;
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
            }
          });
          return future;
        }
      }
