/**
 * This file was auto-generated by Fern from our API Definition.
 */

import core.ClientOptions;
import core.Environment;
import java.lang.String;
import okhttp3.OkHttpClient;

public final class CambApiClientBuilder {
  private ClientOptions.Builder clientOptionsBuilder = ClientOptions.builder();

  private String apiKey = null;

  private Environment environment = Environment.DEFAULT;

  /**
   * Sets apiKey
   */
  public CambApiClientBuilder apiKey(String apiKey) {
    this.apiKey = apiKey;
    return this;
  }

  public CambApiClientBuilder environment(Environment environment) {
    this.environment = environment;
    return this;
  }

  public CambApiClientBuilder url(String url) {
    this.environment = Environment.custom(url);
    return this;
  }

  /**
   * Sets the timeout (in seconds) for the client
   */
  public CambApiClientBuilder timeout(int timeout) {
    this.clientOptionsBuilder.timeout(timeout);
    return this;
  }

  /**
   * Sets the underlying OkHttp client
   */
  public CambApiClientBuilder httpClient(OkHttpClient httpClient) {
    this.clientOptionsBuilder.httpClient(httpClient);
    return this;
  }

  public CambApiClient build() {
    if (apiKey == null) {
      throw new RuntimeException("Please provide apiKey");
    }
    this.clientOptionsBuilder.addHeader("x-api-key", this.apiKey);
    clientOptionsBuilder.environment(this.environment);
    return new CambApiClient(clientOptionsBuilder.build());
  }
}
