/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.texttovoice.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.Nullable;
import core.NullableNonemptyFilter;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateTextToVoiceRequestPayload.Builder.class
)
public final class CreateTextToVoiceRequestPayload {
  private final Optional<String> traceparent;

  private final Optional<String> projectName;

  private final Optional<String> projectDescription;

  private final Optional<Integer> folderId;

  private final String text;

  private final String voiceDescription;

  private final Map<String, Object> additionalProperties;

  private CreateTextToVoiceRequestPayload(Optional<String> traceparent,
      Optional<String> projectName, Optional<String> projectDescription, Optional<Integer> folderId,
      String text, String voiceDescription, Map<String, Object> additionalProperties) {
    this.traceparent = traceparent;
    this.projectName = projectName;
    this.projectDescription = projectDescription;
    this.folderId = folderId;
    this.text = text;
    this.voiceDescription = voiceDescription;
    this.additionalProperties = additionalProperties;
  }

  @JsonIgnore
  public Optional<String> getTraceparent() {
    if (traceparent == null) {
      return Optional.empty();
    }
    return traceparent;
  }

  @JsonIgnore
  public Optional<String> getProjectName() {
    if (projectName == null) {
      return Optional.empty();
    }
    return projectName;
  }

  @JsonIgnore
  public Optional<String> getProjectDescription() {
    if (projectDescription == null) {
      return Optional.empty();
    }
    return projectDescription;
  }

  @JsonIgnore
  public Optional<Integer> getFolderId() {
    if (folderId == null) {
      return Optional.empty();
    }
    return folderId;
  }

  /**
   * @return The text to be converted to voice
   */
  @JsonProperty("text")
  public String getText() {
    return text;
  }

  /**
   * @return Description to use for the created voice
   */
  @JsonProperty("voice_description")
  public String getVoiceDescription() {
    return voiceDescription;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("traceparent")
  private Optional<String> _getTraceparent() {
    return traceparent;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("project_name")
  private Optional<String> _getProjectName() {
    return projectName;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("project_description")
  private Optional<String> _getProjectDescription() {
    return projectDescription;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("folder_id")
  private Optional<Integer> _getFolderId() {
    return folderId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateTextToVoiceRequestPayload && equalTo((CreateTextToVoiceRequestPayload) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateTextToVoiceRequestPayload other) {
    return traceparent.equals(other.traceparent) && projectName.equals(other.projectName) && projectDescription.equals(other.projectDescription) && folderId.equals(other.folderId) && text.equals(other.text) && voiceDescription.equals(other.voiceDescription);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.traceparent, this.projectName, this.projectDescription, this.folderId, this.text, this.voiceDescription);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TextStage builder() {
    return new Builder();
  }

  public interface TextStage {
    VoiceDescriptionStage text(@NotNull String text);

    Builder from(CreateTextToVoiceRequestPayload other);
  }

  public interface VoiceDescriptionStage {
    _FinalStage voiceDescription(@NotNull String voiceDescription);
  }

  public interface _FinalStage {
    CreateTextToVoiceRequestPayload build();

    _FinalStage traceparent(Optional<String> traceparent);

    _FinalStage traceparent(String traceparent);

    _FinalStage traceparent(Nullable<String> traceparent);

    _FinalStage projectName(Optional<String> projectName);

    _FinalStage projectName(String projectName);

    _FinalStage projectName(Nullable<String> projectName);

    _FinalStage projectDescription(Optional<String> projectDescription);

    _FinalStage projectDescription(String projectDescription);

    _FinalStage projectDescription(Nullable<String> projectDescription);

    _FinalStage folderId(Optional<Integer> folderId);

    _FinalStage folderId(Integer folderId);

    _FinalStage folderId(Nullable<Integer> folderId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TextStage, VoiceDescriptionStage, _FinalStage {
    private String text;

    private String voiceDescription;

    private Optional<Integer> folderId = Optional.empty();

    private Optional<String> projectDescription = Optional.empty();

    private Optional<String> projectName = Optional.empty();

    private Optional<String> traceparent = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateTextToVoiceRequestPayload other) {
      traceparent(other.getTraceparent());
      projectName(other.getProjectName());
      projectDescription(other.getProjectDescription());
      folderId(other.getFolderId());
      text(other.getText());
      voiceDescription(other.getVoiceDescription());
      return this;
    }

    /**
     * <p>The text to be converted to voice</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("text")
    public VoiceDescriptionStage text(@NotNull String text) {
      this.text = Objects.requireNonNull(text, "text must not be null");
      return this;
    }

    /**
     * <p>Description to use for the created voice</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("voice_description")
    public _FinalStage voiceDescription(@NotNull String voiceDescription) {
      this.voiceDescription = Objects.requireNonNull(voiceDescription, "voiceDescription must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage folderId(Nullable<Integer> folderId) {
      if (folderId.isNull()) {
        this.folderId = null;
      }
      else if (folderId.isEmpty()) {
        this.folderId = Optional.empty();
      }
      else {
        this.folderId = Optional.of(folderId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage folderId(Integer folderId) {
      this.folderId = Optional.ofNullable(folderId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "folder_id",
        nulls = Nulls.SKIP
    )
    public _FinalStage folderId(Optional<Integer> folderId) {
      this.folderId = folderId;
      return this;
    }

    @java.lang.Override
    public _FinalStage projectDescription(Nullable<String> projectDescription) {
      if (projectDescription.isNull()) {
        this.projectDescription = null;
      }
      else if (projectDescription.isEmpty()) {
        this.projectDescription = Optional.empty();
      }
      else {
        this.projectDescription = Optional.of(projectDescription.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage projectDescription(String projectDescription) {
      this.projectDescription = Optional.ofNullable(projectDescription);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "project_description",
        nulls = Nulls.SKIP
    )
    public _FinalStage projectDescription(Optional<String> projectDescription) {
      this.projectDescription = projectDescription;
      return this;
    }

    @java.lang.Override
    public _FinalStage projectName(Nullable<String> projectName) {
      if (projectName.isNull()) {
        this.projectName = null;
      }
      else if (projectName.isEmpty()) {
        this.projectName = Optional.empty();
      }
      else {
        this.projectName = Optional.of(projectName.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage projectName(String projectName) {
      this.projectName = Optional.ofNullable(projectName);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "project_name",
        nulls = Nulls.SKIP
    )
    public _FinalStage projectName(Optional<String> projectName) {
      this.projectName = projectName;
      return this;
    }

    @java.lang.Override
    public _FinalStage traceparent(Nullable<String> traceparent) {
      if (traceparent.isNull()) {
        this.traceparent = null;
      }
      else if (traceparent.isEmpty()) {
        this.traceparent = Optional.empty();
      }
      else {
        this.traceparent = Optional.of(traceparent.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage traceparent(String traceparent) {
      this.traceparent = Optional.ofNullable(traceparent);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "traceparent",
        nulls = Nulls.SKIP
    )
    public _FinalStage traceparent(Optional<String> traceparent) {
      this.traceparent = traceparent;
      return this;
    }

    @java.lang.Override
    public CreateTextToVoiceRequestPayload build() {
      return new CreateTextToVoiceRequestPayload(traceparent, projectName, projectDescription, folderId, text, voiceDescription, additionalProperties);
    }
  }
}
