/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.texttovoice.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.Nullable;
import core.NullableNonemptyFilter;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetTextToVoiceStatusTextToVoiceTaskIdGetRequest.Builder.class
)
public final class GetTextToVoiceStatusTextToVoiceTaskIdGetRequest {
  private final Optional<String> traceparent;

  private final Optional<Integer> runId;

  private final Map<String, Object> additionalProperties;

  private GetTextToVoiceStatusTextToVoiceTaskIdGetRequest(Optional<String> traceparent,
      Optional<Integer> runId, Map<String, Object> additionalProperties) {
    this.traceparent = traceparent;
    this.runId = runId;
    this.additionalProperties = additionalProperties;
  }

  @JsonIgnore
  public Optional<String> getTraceparent() {
    if (traceparent == null) {
      return Optional.empty();
    }
    return traceparent;
  }

  @JsonIgnore
  public Optional<Integer> getRunId() {
    if (runId == null) {
      return Optional.empty();
    }
    return runId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("traceparent")
  private Optional<String> _getTraceparent() {
    return traceparent;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("run_id")
  private Optional<Integer> _getRunId() {
    return runId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetTextToVoiceStatusTextToVoiceTaskIdGetRequest && equalTo((GetTextToVoiceStatusTextToVoiceTaskIdGetRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetTextToVoiceStatusTextToVoiceTaskIdGetRequest other) {
    return traceparent.equals(other.traceparent) && runId.equals(other.runId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.traceparent, this.runId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> traceparent = Optional.empty();

    private Optional<Integer> runId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(GetTextToVoiceStatusTextToVoiceTaskIdGetRequest other) {
      traceparent(other.getTraceparent());
      runId(other.getRunId());
      return this;
    }

    @JsonSetter(
        value = "traceparent",
        nulls = Nulls.SKIP
    )
    public Builder traceparent(Optional<String> traceparent) {
      this.traceparent = traceparent;
      return this;
    }

    public Builder traceparent(String traceparent) {
      this.traceparent = Optional.ofNullable(traceparent);
      return this;
    }

    public Builder traceparent(Nullable<String> traceparent) {
      if (traceparent.isNull()) {
        this.traceparent = null;
      }
      else if (traceparent.isEmpty()) {
        this.traceparent = Optional.empty();
      }
      else {
        this.traceparent = Optional.of(traceparent.get());
      }
      return this;
    }

    @JsonSetter(
        value = "run_id",
        nulls = Nulls.SKIP
    )
    public Builder runId(Optional<Integer> runId) {
      this.runId = runId;
      return this;
    }

    public Builder runId(Integer runId) {
      this.runId = Optional.ofNullable(runId);
      return this;
    }

    public Builder runId(Nullable<Integer> runId) {
      if (runId.isNull()) {
        this.runId = null;
      }
      else if (runId.isEmpty()) {
        this.runId = Optional.empty();
      }
      else {
        this.runId = Optional.of(runId.get());
      }
      return this;
    }

    public GetTextToVoiceStatusTextToVoiceTaskIdGetRequest build() {
      return new GetTextToVoiceStatusTextToVoiceTaskIdGetRequest(traceparent, runId, additionalProperties);
    }
  }
}
