/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.voicecloning;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.CambApiApiException;
import core.CambApiException;
import core.ClientOptions;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import errors.UnprocessableEntityError;
import java.io.File;
import java.io.IOException;
import java.lang.Exception;
import java.lang.Object;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;
import java.nio.file.Files;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.MediaType;
import okhttp3.MultipartBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;
import resources.voicecloning.requests.BodyCreateCustomVoiceCreateCustomVoicePost;
import resources.voicecloning.requests.ListVoicesListVoicesGetRequest;
import resources.voicecloning.types.ListVoicesListVoicesGetResponseItem;
import types.CreateCustomVoiceOut;
import types.HttpValidationError;

public class AsyncVoiceCloningClient {
  protected final ClientOptions clientOptions;

  public AsyncVoiceCloningClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public CompletableFuture<List<ListVoicesListVoicesGetResponseItem>> listVoices() {
    return listVoices(ListVoicesListVoicesGetRequest.builder().build());
  }

  public CompletableFuture<List<ListVoicesListVoicesGetResponseItem>> listVoices(
      ListVoicesListVoicesGetRequest request) {
    return listVoices(request,null);
  }

  public CompletableFuture<List<ListVoicesListVoicesGetResponseItem>> listVoices(
      ListVoicesListVoicesGetRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("list-voices");if (request.getRunId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<List<ListVoicesListVoicesGetResponseItem>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<List<ListVoicesListVoicesGetResponseItem>>() {}));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 422) {
                future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    public CompletableFuture<CreateCustomVoiceOut> createCustomVoice(File file,
        BodyCreateCustomVoiceCreateCustomVoicePost request) {
      return createCustomVoice(file,request,null);
    }

    public CompletableFuture<CreateCustomVoiceOut> createCustomVoice(File file,
        BodyCreateCustomVoiceCreateCustomVoicePost request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("create-custom-voice");if (request.getRunId().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
        }
        MultipartBody.Builder body = new MultipartBody.Builder().setType(MultipartBody.FORM);
        try {
          body.addFormDataPart("voice_name", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getVoiceName()));
          body.addFormDataPart("gender", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getGender()));
          if (request.getDescription().isPresent()) {
            body.addFormDataPart("description", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getDescription().get()));
          }
          if (request.getPublishVoiceToMarketPlace().isPresent()) {
            body.addFormDataPart("publish_voice_to_market_place", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getPublishVoiceToMarketPlace().get()));
          }
          if (request.getAge().isPresent()) {
            body.addFormDataPart("age", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getAge().get()));
          }
          if (request.getLanguage().isPresent()) {
            body.addFormDataPart("language", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getLanguage().get()));
          }
          if (request.getEnhanceAudio().isPresent()) {
            body.addFormDataPart("enhance_audio", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getEnhanceAudio().get()));
          }
          String fileMimeType = Files.probeContentType(file.toPath());
          MediaType fileMimeTypeMediaType = fileMimeType != null ? MediaType.parse(fileMimeType) : null;
          body.addFormDataPart("file", file.getName(), RequestBody.create(fileMimeTypeMediaType, file));
        }
        catch(Exception e) {
          throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("POST", body.build())
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<CreateCustomVoiceOut> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (response.isSuccessful()) {
                future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CreateCustomVoiceOut.class));
                return;
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              try {
                if (response.code() == 422) {
                  future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        });
        return future;
      }
    }
