/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.dub;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.CambApiApiException;
import core.CambApiException;
import core.ClientOptions;
import core.MediaTypes;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import errors.UnprocessableEntityError;
import java.io.IOException;
import java.lang.Exception;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;
import resources.dub.requests.DubbedOutputInAltFormatRequestPayload;
import resources.dub.requests.EndToEndDubbingRequestPayload;
import resources.dub.requests.GetDubbedOutputInAltFormatStatusDubAltFormatTaskIdGetRequest;
import resources.dub.requests.GetDubbedRunInfoDubResultRunIdGetRequest;
import resources.dub.requests.GetDubbedRunTranscriptTranscriptRunIdLanguageGetRequest;
import resources.dub.requests.GetDubbingRunsResultsDubbingResultsPostRequest;
import resources.dub.requests.GetEndToEndDubbingStatusDubTaskIdGetRequest;
import resources.dub.requests.PollDiscordDubTaskDiscordDubTaskIdGetRequest;
import resources.dub.requests.PollTwitterDubTaskTwitterDubTaskIdGetRequest;
import resources.dub.types.GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse;
import resources.dub.types.GetDubbedRunInfoDubResultRunIdGetResponse;
import resources.dub.types.GetDubbingRunsResultsDubbingResultsPostResponseValue;
import types.HttpValidationError;
import types.OrchestratorPipelineCallResult;
import types.OrchestratorPipelineResult;

public class AsyncDubClient {
  protected final ClientOptions clientOptions;

  public AsyncDubClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public CompletableFuture<OrchestratorPipelineCallResult> endToEndDubbing(
      EndToEndDubbingRequestPayload request) {
    return endToEndDubbing(request,null);
  }

  public CompletableFuture<OrchestratorPipelineCallResult> endToEndDubbing(
      EndToEndDubbingRequestPayload request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("dub");if (request.getRunId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
      }
      Map<String, Object> properties = new HashMap<>();
      if (request.getProjectName().isPresent()) {
        properties.put("project_name", request.getProjectName());
      }
      if (request.getProjectDescription().isPresent()) {
        properties.put("project_description", request.getProjectDescription());
      }
      if (request.getFolderId().isPresent()) {
        properties.put("folder_id", request.getFolderId());
      }
      properties.put("video_url", request.getVideoUrl());
      properties.put("source_language", request.getSourceLanguage());
      if (request.getTargetLanguage().isPresent()) {
        properties.put("target_language", request.getTargetLanguage());
      }
      if (request.getTargetLanguages().isPresent()) {
        properties.put("target_languages", request.getTargetLanguages());
      }
      if (request.getSelectedAudioTracks().isPresent()) {
        properties.put("selected_audio_tracks", request.getSelectedAudioTracks());
      }
      if (request.getAddOutputAsAnAudioTrack().isPresent()) {
        properties.put("add_output_as_an_audio_track", request.getAddOutputAsAnAudioTrack());
      }
      if (request.getChosenDictionaries().isPresent()) {
        properties.put("chosen_dictionaries", request.getChosenDictionaries());
      }
      if (request.getAiOptimization().isPresent()) {
        properties.put("ai_optimization", request.getAiOptimization());
      }
      RequestBody body;
      try {
        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(properties), MediaTypes.APPLICATION_JSON);
      }
      catch(Exception e) {
        throw new RuntimeException(e);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<OrchestratorPipelineCallResult> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineCallResult.class));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 422) {
                future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    public CompletableFuture<OrchestratorPipelineResult> getEndToEndDubbingStatus(String taskId) {
      return getEndToEndDubbingStatus(taskId,GetEndToEndDubbingStatusDubTaskIdGetRequest.builder().build());
    }

    public CompletableFuture<OrchestratorPipelineResult> getEndToEndDubbingStatus(String taskId,
        GetEndToEndDubbingStatusDubTaskIdGetRequest request) {
      return getEndToEndDubbingStatus(taskId,request,null);
    }

    public CompletableFuture<OrchestratorPipelineResult> getEndToEndDubbingStatus(String taskId,
        GetEndToEndDubbingStatusDubTaskIdGetRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("dub")
        .addPathSegment(taskId);if (request.getRunId().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<OrchestratorPipelineResult> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (response.isSuccessful()) {
                future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineResult.class));
                return;
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              try {
                if (response.code() == 422) {
                  future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      /**
       * NOTE: This endpoint should be called only by the users to get values for their runs via API.
       * Further we need to validate if the user has access to the run_id, otherwise we should not return the output urls.
       */
      public CompletableFuture<GetDubbedRunInfoDubResultRunIdGetResponse> getDubbedRunInfo(
          Optional<Integer> runId) {
        return getDubbedRunInfo(runId,GetDubbedRunInfoDubResultRunIdGetRequest.builder().build());
      }

      /**
       * NOTE: This endpoint should be called only by the users to get values for their runs via API.
       * Further we need to validate if the user has access to the run_id, otherwise we should not return the output urls.
       */
      public CompletableFuture<GetDubbedRunInfoDubResultRunIdGetResponse> getDubbedRunInfo(
          Optional<Integer> runId, GetDubbedRunInfoDubResultRunIdGetRequest request) {
        return getDubbedRunInfo(runId,request,null);
      }

      /**
       * NOTE: This endpoint should be called only by the users to get values for their runs via API.
       * Further we need to validate if the user has access to the run_id, otherwise we should not return the output urls.
       */
      public CompletableFuture<GetDubbedRunInfoDubResultRunIdGetResponse> getDubbedRunInfo(
          Optional<Integer> runId, GetDubbedRunInfoDubResultRunIdGetRequest request,
          RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("dub-result");
          if (runId.isPresent()) {
            httpUrl.addPathSegment(runId.get().toString());
          }

          .build();
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl)
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<GetDubbedRunInfoDubResultRunIdGetResponse> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (response.isSuccessful()) {
                future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetDubbedRunInfoDubResultRunIdGetResponse.class));
                return;
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              try {
                if (response.code() == 422) {
                  future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      public CompletableFuture<Map<String, GetDubbingRunsResultsDubbingResultsPostResponseValue>> getDubbingRunsResults(
          GetDubbingRunsResultsDubbingResultsPostRequest request) {
        return getDubbingRunsResults(request,null);
      }

      public CompletableFuture<Map<String, GetDubbingRunsResultsDubbingResultsPostResponseValue>> getDubbingRunsResults(
          GetDubbingRunsResultsDubbingResultsPostRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("dubbing-results");if (request.getRunId().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
          }
          RequestBody body;
          try {
            body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
          }
          catch(Exception e) {
            throw new RuntimeException(e);
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("POST", body)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json");
          if (request.getTraceparent().isPresent()) {
            _requestBuilder.addHeader("traceparent", request.getTraceparent().get());
          }
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<Map<String, GetDubbingRunsResultsDubbingResultsPostResponseValue>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                if (response.isSuccessful()) {
                  future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<Map<String, GetDubbingRunsResultsDubbingResultsPostResponseValue>>() {}));
                  return;
                }
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                try {
                  if (response.code() == 422) {
                    future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                    return;
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        public CompletableFuture<Map<String, String>> getDubbedRunTranscript(
            Optional<Integer> runId, int language) {
          return getDubbedRunTranscript(runId,language,GetDubbedRunTranscriptTranscriptRunIdLanguageGetRequest.builder().build());
        }

        public CompletableFuture<Map<String, String>> getDubbedRunTranscript(
            Optional<Integer> runId, int language,
            GetDubbedRunTranscriptTranscriptRunIdLanguageGetRequest request) {
          return getDubbedRunTranscript(runId,language,request,null);
        }

        public CompletableFuture<Map<String, String>> getDubbedRunTranscript(
            Optional<Integer> runId, int language,
            GetDubbedRunTranscriptTranscriptRunIdLanguageGetRequest request,
            RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("transcript");
            if (runId.isPresent()) {
              httpUrl.addPathSegment(runId.get().toString());
            }

            .addPathSegment(Integer.toString(language))if (request.getFormatType().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "format_type", request.getFormatType().get().toString(), false);
            }
            if (request.getDataType().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "data_type", request.getDataType().get().toString(), false);
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("GET", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json")
              .addHeader("Accept", "application/json");
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<Map<String, String>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  if (response.isSuccessful()) {
                    future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<Map<String, String>>() {}));
                    return;
                  }
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  try {
                    if (response.code() == 422) {
                      future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                      return;
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
              }
            });
            return future;
          }

          public CompletableFuture<GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse> getDubbedOutputInAltFormat(
              Optional<Integer> runId, int language,
              DubbedOutputInAltFormatRequestPayload request) {
            return getDubbedOutputInAltFormat(runId,language,request,null);
          }

          public CompletableFuture<GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse> getDubbedOutputInAltFormat(
              Optional<Integer> runId, int language, DubbedOutputInAltFormatRequestPayload request,
              RequestOptions requestOptions) {
            HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("dub-alt-format");
              if (runId.isPresent()) {
                httpUrl.addPathSegment(runId.get().toString());
              }

              .addPathSegment(Integer.toString(language))
              .build();
            RequestBody body;
            try {
              body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
            }
            catch(JsonProcessingException e) {
              throw new CambApiException("Failed to serialize request", e);
            }
            Request okhttpRequest = new Request.Builder()
              .url(httpUrl)
              .method("POST", body)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json")
              .addHeader("Accept", "application/json")
              .build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  if (response.isSuccessful()) {
                    future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetDubbedOutputInAltFormatDubAltFormatRunIdLanguagePostResponse.class));
                    return;
                  }
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  try {
                    if (response.code() == 422) {
                      future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                      return;
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
              }
            });
            return future;
          }

          public CompletableFuture<OrchestratorPipelineResult> getDubbedOutputInAltFormatStatus(
              String taskId) {
            return getDubbedOutputInAltFormatStatus(taskId,GetDubbedOutputInAltFormatStatusDubAltFormatTaskIdGetRequest.builder().build());
          }

          public CompletableFuture<OrchestratorPipelineResult> getDubbedOutputInAltFormatStatus(
              String taskId, GetDubbedOutputInAltFormatStatusDubAltFormatTaskIdGetRequest request) {
            return getDubbedOutputInAltFormatStatus(taskId,request,null);
          }

          public CompletableFuture<OrchestratorPipelineResult> getDubbedOutputInAltFormatStatus(
              String taskId, GetDubbedOutputInAltFormatStatusDubAltFormatTaskIdGetRequest request,
              RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("dub-alt-format")
              .addPathSegment(taskId);if (request.getRunId().isPresent()) {
                QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
              }
              Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
              Request okhttpRequest = _requestBuilder.build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              CompletableFuture<OrchestratorPipelineResult> future = new CompletableFuture<>();
              client.newCall(okhttpRequest).enqueue(new Callback() {
                @Override
                public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                  try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                      future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineResult.class));
                      return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                      if (response.code() == 422) {
                        future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                        return;
                      }
                    }
                    catch (JsonProcessingException ignored) {
                      // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                    return;
                  }
                  catch (IOException e) {
                    future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                  }
                }

                @Override
                public void onFailure(@NotNull Call call, @NotNull IOException e) {
                  future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                }
              });
              return future;
            }

            public CompletableFuture<OrchestratorPipelineResult> pollDiscordDubTask(String taskId) {
              return pollDiscordDubTask(taskId,PollDiscordDubTaskDiscordDubTaskIdGetRequest.builder().build());
            }

            public CompletableFuture<OrchestratorPipelineResult> pollDiscordDubTask(String taskId,
                PollDiscordDubTaskDiscordDubTaskIdGetRequest request) {
              return pollDiscordDubTask(taskId,request,null);
            }

            public CompletableFuture<OrchestratorPipelineResult> pollDiscordDubTask(String taskId,
                PollDiscordDubTaskDiscordDubTaskIdGetRequest request,
                RequestOptions requestOptions) {
              HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                .addPathSegments("discord/dub")
                .addPathSegment(taskId);if (request.getRunId().isPresent()) {
                  QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
                }
                Request.Builder _requestBuilder = new Request.Builder()
                  .url(httpUrl.build())
                  .method("GET", null)
                  .headers(Headers.of(clientOptions.headers(requestOptions)))
                  .addHeader("Content-Type", "application/json")
                  .addHeader("Accept", "application/json");
                Request okhttpRequest = _requestBuilder.build();
                OkHttpClient client = clientOptions.httpClient();
                if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                  client = clientOptions.httpClientWithTimeout(requestOptions);
                }
                CompletableFuture<OrchestratorPipelineResult> future = new CompletableFuture<>();
                client.newCall(okhttpRequest).enqueue(new Callback() {
                  @Override
                  public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                    try (ResponseBody responseBody = response.body()) {
                      if (response.isSuccessful()) {
                        future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineResult.class));
                        return;
                      }
                      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                      try {
                        if (response.code() == 422) {
                          future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                          return;
                        }
                      }
                      catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                      }
                      future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                      return;
                    }
                    catch (IOException e) {
                      future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                    }
                  }

                  @Override
                  public void onFailure(@NotNull Call call, @NotNull IOException e) {
                    future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                  }
                });
                return future;
              }

              public CompletableFuture<OrchestratorPipelineResult> pollTwitterDubTask(
                  String taskId) {
                return pollTwitterDubTask(taskId,PollTwitterDubTaskTwitterDubTaskIdGetRequest.builder().build());
              }

              public CompletableFuture<OrchestratorPipelineResult> pollTwitterDubTask(String taskId,
                  PollTwitterDubTaskTwitterDubTaskIdGetRequest request) {
                return pollTwitterDubTask(taskId,request,null);
              }

              public CompletableFuture<OrchestratorPipelineResult> pollTwitterDubTask(String taskId,
                  PollTwitterDubTaskTwitterDubTaskIdGetRequest request,
                  RequestOptions requestOptions) {
                HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                  .addPathSegments("twitter/dub")
                  .addPathSegment(taskId);if (request.getRunId().isPresent()) {
                    QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
                  }
                  Request.Builder _requestBuilder = new Request.Builder()
                    .url(httpUrl.build())
                    .method("GET", null)
                    .headers(Headers.of(clientOptions.headers(requestOptions)))
                    .addHeader("Content-Type", "application/json")
                    .addHeader("Accept", "application/json");
                  Request okhttpRequest = _requestBuilder.build();
                  OkHttpClient client = clientOptions.httpClient();
                  if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                    client = clientOptions.httpClientWithTimeout(requestOptions);
                  }
                  CompletableFuture<OrchestratorPipelineResult> future = new CompletableFuture<>();
                  client.newCall(okhttpRequest).enqueue(new Callback() {
                    @Override
                    public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                      try (ResponseBody responseBody = response.body()) {
                        if (response.isSuccessful()) {
                          future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineResult.class));
                          return;
                        }
                        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                        try {
                          if (response.code() == 422) {
                            future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                            return;
                          }
                        }
                        catch (JsonProcessingException ignored) {
                          // unable to map error response, throwing generic error
                        }
                        future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                        return;
                      }
                      catch (IOException e) {
                        future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                      }
                    }

                    @Override
                    public void onFailure(@NotNull Call call, @NotNull IOException e) {
                      future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
                    }
                  });
                  return future;
                }
              }
