/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.Nullable;
import core.NullableNonemptyFilter;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DataStream.Builder.class
)
public final class DataStream {
  private final int index;

  private final Optional<String> codecName;

  private final Optional<String> codecLongName;

  private final Optional<String> codecTagString;

  private final Optional<String> codecTag;

  private final Optional<String> id;

  private final Map<String, Object> additionalProperties;

  private DataStream(int index, Optional<String> codecName, Optional<String> codecLongName,
      Optional<String> codecTagString, Optional<String> codecTag, Optional<String> id,
      Map<String, Object> additionalProperties) {
    this.index = index;
    this.codecName = codecName;
    this.codecLongName = codecLongName;
    this.codecTagString = codecTagString;
    this.codecTag = codecTag;
    this.id = id;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("index")
  public int getIndex() {
    return index;
  }

  @JsonIgnore
  public Optional<String> getCodecName() {
    if (codecName == null) {
      return Optional.empty();
    }
    return codecName;
  }

  @JsonIgnore
  public Optional<String> getCodecLongName() {
    if (codecLongName == null) {
      return Optional.empty();
    }
    return codecLongName;
  }

  @JsonIgnore
  public Optional<String> getCodecTagString() {
    if (codecTagString == null) {
      return Optional.empty();
    }
    return codecTagString;
  }

  @JsonIgnore
  public Optional<String> getCodecTag() {
    if (codecTag == null) {
      return Optional.empty();
    }
    return codecTag;
  }

  @JsonIgnore
  public Optional<String> getId() {
    if (id == null) {
      return Optional.empty();
    }
    return id;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("codec_name")
  private Optional<String> _getCodecName() {
    return codecName;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("codec_long_name")
  private Optional<String> _getCodecLongName() {
    return codecLongName;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("codec_tag_string")
  private Optional<String> _getCodecTagString() {
    return codecTagString;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("codec_tag")
  private Optional<String> _getCodecTag() {
    return codecTag;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("id")
  private Optional<String> _getId() {
    return id;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DataStream && equalTo((DataStream) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(DataStream other) {
    return index == other.index && codecName.equals(other.codecName) && codecLongName.equals(other.codecLongName) && codecTagString.equals(other.codecTagString) && codecTag.equals(other.codecTag) && id.equals(other.id);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.index, this.codecName, this.codecLongName, this.codecTagString, this.codecTag, this.id);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IndexStage builder() {
    return new Builder();
  }

  public interface IndexStage {
    _FinalStage index(int index);

    Builder from(DataStream other);
  }

  public interface _FinalStage {
    DataStream build();

    _FinalStage codecName(Optional<String> codecName);

    _FinalStage codecName(String codecName);

    _FinalStage codecName(Nullable<String> codecName);

    _FinalStage codecLongName(Optional<String> codecLongName);

    _FinalStage codecLongName(String codecLongName);

    _FinalStage codecLongName(Nullable<String> codecLongName);

    _FinalStage codecTagString(Optional<String> codecTagString);

    _FinalStage codecTagString(String codecTagString);

    _FinalStage codecTagString(Nullable<String> codecTagString);

    _FinalStage codecTag(Optional<String> codecTag);

    _FinalStage codecTag(String codecTag);

    _FinalStage codecTag(Nullable<String> codecTag);

    _FinalStage id(Optional<String> id);

    _FinalStage id(String id);

    _FinalStage id(Nullable<String> id);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IndexStage, _FinalStage {
    private int index;

    private Optional<String> id = Optional.empty();

    private Optional<String> codecTag = Optional.empty();

    private Optional<String> codecTagString = Optional.empty();

    private Optional<String> codecLongName = Optional.empty();

    private Optional<String> codecName = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(DataStream other) {
      index(other.getIndex());
      codecName(other.getCodecName());
      codecLongName(other.getCodecLongName());
      codecTagString(other.getCodecTagString());
      codecTag(other.getCodecTag());
      id(other.getId());
      return this;
    }

    @java.lang.Override
    @JsonSetter("index")
    public _FinalStage index(int index) {
      this.index = index;
      return this;
    }

    @java.lang.Override
    public _FinalStage id(Nullable<String> id) {
      if (id.isNull()) {
        this.id = null;
      }
      else if (id.isEmpty()) {
        this.id = Optional.empty();
      }
      else {
        this.id = Optional.of(id.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage id(String id) {
      this.id = Optional.ofNullable(id);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "id",
        nulls = Nulls.SKIP
    )
    public _FinalStage id(Optional<String> id) {
      this.id = id;
      return this;
    }

    @java.lang.Override
    public _FinalStage codecTag(Nullable<String> codecTag) {
      if (codecTag.isNull()) {
        this.codecTag = null;
      }
      else if (codecTag.isEmpty()) {
        this.codecTag = Optional.empty();
      }
      else {
        this.codecTag = Optional.of(codecTag.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage codecTag(String codecTag) {
      this.codecTag = Optional.ofNullable(codecTag);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "codec_tag",
        nulls = Nulls.SKIP
    )
    public _FinalStage codecTag(Optional<String> codecTag) {
      this.codecTag = codecTag;
      return this;
    }

    @java.lang.Override
    public _FinalStage codecTagString(Nullable<String> codecTagString) {
      if (codecTagString.isNull()) {
        this.codecTagString = null;
      }
      else if (codecTagString.isEmpty()) {
        this.codecTagString = Optional.empty();
      }
      else {
        this.codecTagString = Optional.of(codecTagString.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage codecTagString(String codecTagString) {
      this.codecTagString = Optional.ofNullable(codecTagString);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "codec_tag_string",
        nulls = Nulls.SKIP
    )
    public _FinalStage codecTagString(Optional<String> codecTagString) {
      this.codecTagString = codecTagString;
      return this;
    }

    @java.lang.Override
    public _FinalStage codecLongName(Nullable<String> codecLongName) {
      if (codecLongName.isNull()) {
        this.codecLongName = null;
      }
      else if (codecLongName.isEmpty()) {
        this.codecLongName = Optional.empty();
      }
      else {
        this.codecLongName = Optional.of(codecLongName.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage codecLongName(String codecLongName) {
      this.codecLongName = Optional.ofNullable(codecLongName);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "codec_long_name",
        nulls = Nulls.SKIP
    )
    public _FinalStage codecLongName(Optional<String> codecLongName) {
      this.codecLongName = codecLongName;
      return this;
    }

    @java.lang.Override
    public _FinalStage codecName(Nullable<String> codecName) {
      if (codecName.isNull()) {
        this.codecName = null;
      }
      else if (codecName.isEmpty()) {
        this.codecName = Optional.empty();
      }
      else {
        this.codecName = Optional.of(codecName.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage codecName(String codecName) {
      this.codecName = Optional.ofNullable(codecName);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "codec_name",
        nulls = Nulls.SKIP
    )
    public _FinalStage codecName(Optional<String> codecName) {
      this.codecName = codecName;
      return this;
    }

    @java.lang.Override
    public DataStream build() {
      return new DataStream(index, codecName, codecLongName, codecTagString, codecTag, id, additionalProperties);
    }
  }
}
