/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.Nullable;
import core.NullableNonemptyFilter;
import core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DictionaryWithTerms.Builder.class
)
public final class DictionaryWithTerms {
  private final int id;

  private final String name;

  private final Optional<String> description;

  private final Optional<OffsetDateTime> createdAt;

  private final Optional<OffsetDateTime> lastEditedAt;

  private final Optional<List<DictionaryTerm>> dictionaryTerms;

  private final Optional<List<Integer>> languages;

  private final Map<String, Object> additionalProperties;

  private DictionaryWithTerms(int id, String name, Optional<String> description,
      Optional<OffsetDateTime> createdAt, Optional<OffsetDateTime> lastEditedAt,
      Optional<List<DictionaryTerm>> dictionaryTerms, Optional<List<Integer>> languages,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.createdAt = createdAt;
    this.lastEditedAt = lastEditedAt;
    this.dictionaryTerms = dictionaryTerms;
    this.languages = languages;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public int getId() {
    return id;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonIgnore
  public Optional<String> getDescription() {
    if (description == null) {
      return Optional.empty();
    }
    return description;
  }

  @JsonIgnore
  public Optional<OffsetDateTime> getCreatedAt() {
    if (createdAt == null) {
      return Optional.empty();
    }
    return createdAt;
  }

  @JsonIgnore
  public Optional<OffsetDateTime> getLastEditedAt() {
    if (lastEditedAt == null) {
      return Optional.empty();
    }
    return lastEditedAt;
  }

  @JsonIgnore
  public Optional<List<DictionaryTerm>> getDictionaryTerms() {
    if (dictionaryTerms == null) {
      return Optional.empty();
    }
    return dictionaryTerms;
  }

  @JsonIgnore
  public Optional<List<Integer>> getLanguages() {
    if (languages == null) {
      return Optional.empty();
    }
    return languages;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("description")
  private Optional<String> _getDescription() {
    return description;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("created_at")
  private Optional<OffsetDateTime> _getCreatedAt() {
    return createdAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("last_edited_at")
  private Optional<OffsetDateTime> _getLastEditedAt() {
    return lastEditedAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("dictionary_terms")
  private Optional<List<DictionaryTerm>> _getDictionaryTerms() {
    return dictionaryTerms;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("languages")
  private Optional<List<Integer>> _getLanguages() {
    return languages;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DictionaryWithTerms && equalTo((DictionaryWithTerms) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(DictionaryWithTerms other) {
    return id == other.id && name.equals(other.name) && description.equals(other.description) && createdAt.equals(other.createdAt) && lastEditedAt.equals(other.lastEditedAt) && dictionaryTerms.equals(other.dictionaryTerms) && languages.equals(other.languages);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.name, this.description, this.createdAt, this.lastEditedAt, this.dictionaryTerms, this.languages);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    NameStage id(int id);

    Builder from(DictionaryWithTerms other);
  }

  public interface NameStage {
    _FinalStage name(@NotNull String name);
  }

  public interface _FinalStage {
    DictionaryWithTerms build();

    _FinalStage description(Optional<String> description);

    _FinalStage description(String description);

    _FinalStage description(Nullable<String> description);

    _FinalStage createdAt(Optional<OffsetDateTime> createdAt);

    _FinalStage createdAt(OffsetDateTime createdAt);

    _FinalStage createdAt(Nullable<OffsetDateTime> createdAt);

    _FinalStage lastEditedAt(Optional<OffsetDateTime> lastEditedAt);

    _FinalStage lastEditedAt(OffsetDateTime lastEditedAt);

    _FinalStage lastEditedAt(Nullable<OffsetDateTime> lastEditedAt);

    _FinalStage dictionaryTerms(Optional<List<DictionaryTerm>> dictionaryTerms);

    _FinalStage dictionaryTerms(List<DictionaryTerm> dictionaryTerms);

    _FinalStage dictionaryTerms(Nullable<List<DictionaryTerm>> dictionaryTerms);

    _FinalStage languages(Optional<List<Integer>> languages);

    _FinalStage languages(List<Integer> languages);

    _FinalStage languages(Nullable<List<Integer>> languages);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, NameStage, _FinalStage {
    private int id;

    private String name;

    private Optional<List<Integer>> languages = Optional.empty();

    private Optional<List<DictionaryTerm>> dictionaryTerms = Optional.empty();

    private Optional<OffsetDateTime> lastEditedAt = Optional.empty();

    private Optional<OffsetDateTime> createdAt = Optional.empty();

    private Optional<String> description = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(DictionaryWithTerms other) {
      id(other.getId());
      name(other.getName());
      description(other.getDescription());
      createdAt(other.getCreatedAt());
      lastEditedAt(other.getLastEditedAt());
      dictionaryTerms(other.getDictionaryTerms());
      languages(other.getLanguages());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public NameStage id(int id) {
      this.id = id;
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public _FinalStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage languages(Nullable<List<Integer>> languages) {
      if (languages.isNull()) {
        this.languages = null;
      }
      else if (languages.isEmpty()) {
        this.languages = Optional.empty();
      }
      else {
        this.languages = Optional.of(languages.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage languages(List<Integer> languages) {
      this.languages = Optional.ofNullable(languages);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "languages",
        nulls = Nulls.SKIP
    )
    public _FinalStage languages(Optional<List<Integer>> languages) {
      this.languages = languages;
      return this;
    }

    @java.lang.Override
    public _FinalStage dictionaryTerms(Nullable<List<DictionaryTerm>> dictionaryTerms) {
      if (dictionaryTerms.isNull()) {
        this.dictionaryTerms = null;
      }
      else if (dictionaryTerms.isEmpty()) {
        this.dictionaryTerms = Optional.empty();
      }
      else {
        this.dictionaryTerms = Optional.of(dictionaryTerms.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage dictionaryTerms(List<DictionaryTerm> dictionaryTerms) {
      this.dictionaryTerms = Optional.ofNullable(dictionaryTerms);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "dictionary_terms",
        nulls = Nulls.SKIP
    )
    public _FinalStage dictionaryTerms(Optional<List<DictionaryTerm>> dictionaryTerms) {
      this.dictionaryTerms = dictionaryTerms;
      return this;
    }

    @java.lang.Override
    public _FinalStage lastEditedAt(Nullable<OffsetDateTime> lastEditedAt) {
      if (lastEditedAt.isNull()) {
        this.lastEditedAt = null;
      }
      else if (lastEditedAt.isEmpty()) {
        this.lastEditedAt = Optional.empty();
      }
      else {
        this.lastEditedAt = Optional.of(lastEditedAt.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage lastEditedAt(OffsetDateTime lastEditedAt) {
      this.lastEditedAt = Optional.ofNullable(lastEditedAt);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "last_edited_at",
        nulls = Nulls.SKIP
    )
    public _FinalStage lastEditedAt(Optional<OffsetDateTime> lastEditedAt) {
      this.lastEditedAt = lastEditedAt;
      return this;
    }

    @java.lang.Override
    public _FinalStage createdAt(Nullable<OffsetDateTime> createdAt) {
      if (createdAt.isNull()) {
        this.createdAt = null;
      }
      else if (createdAt.isEmpty()) {
        this.createdAt = Optional.empty();
      }
      else {
        this.createdAt = Optional.of(createdAt.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage createdAt(OffsetDateTime createdAt) {
      this.createdAt = Optional.ofNullable(createdAt);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "created_at",
        nulls = Nulls.SKIP
    )
    public _FinalStage createdAt(Optional<OffsetDateTime> createdAt) {
      this.createdAt = createdAt;
      return this;
    }

    @java.lang.Override
    public _FinalStage description(Nullable<String> description) {
      if (description.isNull()) {
        this.description = null;
      }
      else if (description.isEmpty()) {
        this.description = Optional.empty();
      }
      else {
        this.description = Optional.of(description.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public _FinalStage description(Optional<String> description) {
      this.description = description;
      return this;
    }

    @java.lang.Override
    public DictionaryWithTerms build() {
      return new DictionaryWithTerms(id, name, description, createdAt, lastEditedAt, dictionaryTerms, languages, additionalProperties);
    }
  }
}
