/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.Nullable;
import core.NullableNonemptyFilter;
import core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SourceStream.Builder.class
)
public final class SourceStream {
  private final int language;

  private final String url;

  private final Optional<Integer> category;

  private final Optional<String> passphrase;

  private final Optional<String> streamid;

  private final Optional<Integer> numberOfStreams;

  private final Optional<Integer> audioStream;

  private final Optional<Integer> backgroundAudioStream;

  private final Optional<Integer> latency;

  private final Optional<Boolean> relayInput;

  private final Map<String, Object> additionalProperties;

  private SourceStream(int language, String url, Optional<Integer> category,
      Optional<String> passphrase, Optional<String> streamid, Optional<Integer> numberOfStreams,
      Optional<Integer> audioStream, Optional<Integer> backgroundAudioStream,
      Optional<Integer> latency, Optional<Boolean> relayInput,
      Map<String, Object> additionalProperties) {
    this.language = language;
    this.url = url;
    this.category = category;
    this.passphrase = passphrase;
    this.streamid = streamid;
    this.numberOfStreams = numberOfStreams;
    this.audioStream = audioStream;
    this.backgroundAudioStream = backgroundAudioStream;
    this.latency = latency;
    this.relayInput = relayInput;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("language")
  public int getLanguage() {
    return language;
  }

  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  @JsonIgnore
  public Optional<Integer> getCategory() {
    if (category == null) {
      return Optional.empty();
    }
    return category;
  }

  @JsonIgnore
  public Optional<String> getPassphrase() {
    if (passphrase == null) {
      return Optional.empty();
    }
    return passphrase;
  }

  @JsonIgnore
  public Optional<String> getStreamid() {
    if (streamid == null) {
      return Optional.empty();
    }
    return streamid;
  }

  @JsonIgnore
  public Optional<Integer> getNumberOfStreams() {
    if (numberOfStreams == null) {
      return Optional.empty();
    }
    return numberOfStreams;
  }

  @JsonIgnore
  public Optional<Integer> getAudioStream() {
    if (audioStream == null) {
      return Optional.empty();
    }
    return audioStream;
  }

  @JsonIgnore
  public Optional<Integer> getBackgroundAudioStream() {
    if (backgroundAudioStream == null) {
      return Optional.empty();
    }
    return backgroundAudioStream;
  }

  @JsonIgnore
  public Optional<Integer> getLatency() {
    if (latency == null) {
      return Optional.empty();
    }
    return latency;
  }

  @JsonIgnore
  public Optional<Boolean> getRelayInput() {
    if (relayInput == null) {
      return Optional.empty();
    }
    return relayInput;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("category")
  private Optional<Integer> _getCategory() {
    return category;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("passphrase")
  private Optional<String> _getPassphrase() {
    return passphrase;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("streamid")
  private Optional<String> _getStreamid() {
    return streamid;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("number_of_streams")
  private Optional<Integer> _getNumberOfStreams() {
    return numberOfStreams;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("audio_stream")
  private Optional<Integer> _getAudioStream() {
    return audioStream;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("background_audio_stream")
  private Optional<Integer> _getBackgroundAudioStream() {
    return backgroundAudioStream;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("latency")
  private Optional<Integer> _getLatency() {
    return latency;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("relay_input")
  private Optional<Boolean> _getRelayInput() {
    return relayInput;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SourceStream && equalTo((SourceStream) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SourceStream other) {
    return language == other.language && url.equals(other.url) && category.equals(other.category) && passphrase.equals(other.passphrase) && streamid.equals(other.streamid) && numberOfStreams.equals(other.numberOfStreams) && audioStream.equals(other.audioStream) && backgroundAudioStream.equals(other.backgroundAudioStream) && latency.equals(other.latency) && relayInput.equals(other.relayInput);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.language, this.url, this.category, this.passphrase, this.streamid, this.numberOfStreams, this.audioStream, this.backgroundAudioStream, this.latency, this.relayInput);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static LanguageStage builder() {
    return new Builder();
  }

  public interface LanguageStage {
    UrlStage language(int language);

    Builder from(SourceStream other);
  }

  public interface UrlStage {
    _FinalStage url(@NotNull String url);
  }

  public interface _FinalStage {
    SourceStream build();

    _FinalStage category(Optional<Integer> category);

    _FinalStage category(Integer category);

    _FinalStage category(Nullable<Integer> category);

    _FinalStage passphrase(Optional<String> passphrase);

    _FinalStage passphrase(String passphrase);

    _FinalStage passphrase(Nullable<String> passphrase);

    _FinalStage streamid(Optional<String> streamid);

    _FinalStage streamid(String streamid);

    _FinalStage streamid(Nullable<String> streamid);

    _FinalStage numberOfStreams(Optional<Integer> numberOfStreams);

    _FinalStage numberOfStreams(Integer numberOfStreams);

    _FinalStage numberOfStreams(Nullable<Integer> numberOfStreams);

    _FinalStage audioStream(Optional<Integer> audioStream);

    _FinalStage audioStream(Integer audioStream);

    _FinalStage audioStream(Nullable<Integer> audioStream);

    _FinalStage backgroundAudioStream(Optional<Integer> backgroundAudioStream);

    _FinalStage backgroundAudioStream(Integer backgroundAudioStream);

    _FinalStage backgroundAudioStream(Nullable<Integer> backgroundAudioStream);

    _FinalStage latency(Optional<Integer> latency);

    _FinalStage latency(Integer latency);

    _FinalStage latency(Nullable<Integer> latency);

    _FinalStage relayInput(Optional<Boolean> relayInput);

    _FinalStage relayInput(Boolean relayInput);

    _FinalStage relayInput(Nullable<Boolean> relayInput);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements LanguageStage, UrlStage, _FinalStage {
    private int language;

    private String url;

    private Optional<Boolean> relayInput = Optional.empty();

    private Optional<Integer> latency = Optional.empty();

    private Optional<Integer> backgroundAudioStream = Optional.empty();

    private Optional<Integer> audioStream = Optional.empty();

    private Optional<Integer> numberOfStreams = Optional.empty();

    private Optional<String> streamid = Optional.empty();

    private Optional<String> passphrase = Optional.empty();

    private Optional<Integer> category = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(SourceStream other) {
      language(other.getLanguage());
      url(other.getUrl());
      category(other.getCategory());
      passphrase(other.getPassphrase());
      streamid(other.getStreamid());
      numberOfStreams(other.getNumberOfStreams());
      audioStream(other.getAudioStream());
      backgroundAudioStream(other.getBackgroundAudioStream());
      latency(other.getLatency());
      relayInput(other.getRelayInput());
      return this;
    }

    @java.lang.Override
    @JsonSetter("language")
    public UrlStage language(int language) {
      this.language = language;
      return this;
    }

    @java.lang.Override
    @JsonSetter("url")
    public _FinalStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage relayInput(Nullable<Boolean> relayInput) {
      if (relayInput.isNull()) {
        this.relayInput = null;
      }
      else if (relayInput.isEmpty()) {
        this.relayInput = Optional.empty();
      }
      else {
        this.relayInput = Optional.of(relayInput.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage relayInput(Boolean relayInput) {
      this.relayInput = Optional.ofNullable(relayInput);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "relay_input",
        nulls = Nulls.SKIP
    )
    public _FinalStage relayInput(Optional<Boolean> relayInput) {
      this.relayInput = relayInput;
      return this;
    }

    @java.lang.Override
    public _FinalStage latency(Nullable<Integer> latency) {
      if (latency.isNull()) {
        this.latency = null;
      }
      else if (latency.isEmpty()) {
        this.latency = Optional.empty();
      }
      else {
        this.latency = Optional.of(latency.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage latency(Integer latency) {
      this.latency = Optional.ofNullable(latency);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "latency",
        nulls = Nulls.SKIP
    )
    public _FinalStage latency(Optional<Integer> latency) {
      this.latency = latency;
      return this;
    }

    @java.lang.Override
    public _FinalStage backgroundAudioStream(Nullable<Integer> backgroundAudioStream) {
      if (backgroundAudioStream.isNull()) {
        this.backgroundAudioStream = null;
      }
      else if (backgroundAudioStream.isEmpty()) {
        this.backgroundAudioStream = Optional.empty();
      }
      else {
        this.backgroundAudioStream = Optional.of(backgroundAudioStream.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage backgroundAudioStream(Integer backgroundAudioStream) {
      this.backgroundAudioStream = Optional.ofNullable(backgroundAudioStream);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "background_audio_stream",
        nulls = Nulls.SKIP
    )
    public _FinalStage backgroundAudioStream(Optional<Integer> backgroundAudioStream) {
      this.backgroundAudioStream = backgroundAudioStream;
      return this;
    }

    @java.lang.Override
    public _FinalStage audioStream(Nullable<Integer> audioStream) {
      if (audioStream.isNull()) {
        this.audioStream = null;
      }
      else if (audioStream.isEmpty()) {
        this.audioStream = Optional.empty();
      }
      else {
        this.audioStream = Optional.of(audioStream.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage audioStream(Integer audioStream) {
      this.audioStream = Optional.ofNullable(audioStream);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "audio_stream",
        nulls = Nulls.SKIP
    )
    public _FinalStage audioStream(Optional<Integer> audioStream) {
      this.audioStream = audioStream;
      return this;
    }

    @java.lang.Override
    public _FinalStage numberOfStreams(Nullable<Integer> numberOfStreams) {
      if (numberOfStreams.isNull()) {
        this.numberOfStreams = null;
      }
      else if (numberOfStreams.isEmpty()) {
        this.numberOfStreams = Optional.empty();
      }
      else {
        this.numberOfStreams = Optional.of(numberOfStreams.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage numberOfStreams(Integer numberOfStreams) {
      this.numberOfStreams = Optional.ofNullable(numberOfStreams);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "number_of_streams",
        nulls = Nulls.SKIP
    )
    public _FinalStage numberOfStreams(Optional<Integer> numberOfStreams) {
      this.numberOfStreams = numberOfStreams;
      return this;
    }

    @java.lang.Override
    public _FinalStage streamid(Nullable<String> streamid) {
      if (streamid.isNull()) {
        this.streamid = null;
      }
      else if (streamid.isEmpty()) {
        this.streamid = Optional.empty();
      }
      else {
        this.streamid = Optional.of(streamid.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage streamid(String streamid) {
      this.streamid = Optional.ofNullable(streamid);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "streamid",
        nulls = Nulls.SKIP
    )
    public _FinalStage streamid(Optional<String> streamid) {
      this.streamid = streamid;
      return this;
    }

    @java.lang.Override
    public _FinalStage passphrase(Nullable<String> passphrase) {
      if (passphrase.isNull()) {
        this.passphrase = null;
      }
      else if (passphrase.isEmpty()) {
        this.passphrase = Optional.empty();
      }
      else {
        this.passphrase = Optional.of(passphrase.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage passphrase(String passphrase) {
      this.passphrase = Optional.ofNullable(passphrase);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "passphrase",
        nulls = Nulls.SKIP
    )
    public _FinalStage passphrase(Optional<String> passphrase) {
      this.passphrase = passphrase;
      return this;
    }

    @java.lang.Override
    public _FinalStage category(Nullable<Integer> category) {
      if (category.isNull()) {
        this.category = null;
      }
      else if (category.isEmpty()) {
        this.category = Optional.empty();
      }
      else {
        this.category = Optional.of(category.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage category(Integer category) {
      this.category = Optional.ofNullable(category);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "category",
        nulls = Nulls.SKIP
    )
    public _FinalStage category(Optional<Integer> category) {
      this.category = category;
      return this;
    }

    @java.lang.Override
    public SourceStream build() {
      return new SourceStream(language, url, category, passphrase, streamid, numberOfStreams, audioStream, backgroundAudioStream, latency, relayInput, additionalProperties);
    }
  }
}
