/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.Nullable;
import core.NullableNonemptyFilter;
import core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TargetStream.Builder.class
)
public final class TargetStream {
  private final List<Integer> languages;

  private final String url;

  private final int type;

  private final Optional<String> passphrase;

  private final Optional<String> streamid;

  private final Optional<List<Optional<Integer>>> pids;

  private final Optional<Boolean> transcodeVideo;

  private final Optional<Boolean> embedSubtitles;

  private final Optional<String> audioCodec;

  private final Optional<String> audioBitrate;

  private final Optional<String> audioChannelLayout;

  private final Optional<Integer> latency;

  private final Optional<Boolean> constantBitrate;

  private final Optional<Boolean> relayOutput;

  private final Map<String, Object> additionalProperties;

  private TargetStream(List<Integer> languages, String url, int type, Optional<String> passphrase,
      Optional<String> streamid, Optional<List<Optional<Integer>>> pids,
      Optional<Boolean> transcodeVideo, Optional<Boolean> embedSubtitles,
      Optional<String> audioCodec, Optional<String> audioBitrate,
      Optional<String> audioChannelLayout, Optional<Integer> latency,
      Optional<Boolean> constantBitrate, Optional<Boolean> relayOutput,
      Map<String, Object> additionalProperties) {
    this.languages = languages;
    this.url = url;
    this.type = type;
    this.passphrase = passphrase;
    this.streamid = streamid;
    this.pids = pids;
    this.transcodeVideo = transcodeVideo;
    this.embedSubtitles = embedSubtitles;
    this.audioCodec = audioCodec;
    this.audioBitrate = audioBitrate;
    this.audioChannelLayout = audioChannelLayout;
    this.latency = latency;
    this.constantBitrate = constantBitrate;
    this.relayOutput = relayOutput;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("languages")
  public List<Integer> getLanguages() {
    return languages;
  }

  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  @JsonProperty("type")
  public int getType() {
    return type;
  }

  @JsonIgnore
  public Optional<String> getPassphrase() {
    if (passphrase == null) {
      return Optional.empty();
    }
    return passphrase;
  }

  @JsonIgnore
  public Optional<String> getStreamid() {
    if (streamid == null) {
      return Optional.empty();
    }
    return streamid;
  }

  @JsonIgnore
  public Optional<List<Optional<Integer>>> getPids() {
    if (pids == null) {
      return Optional.empty();
    }
    return pids;
  }

  @JsonIgnore
  public Optional<Boolean> getTranscodeVideo() {
    if (transcodeVideo == null) {
      return Optional.empty();
    }
    return transcodeVideo;
  }

  @JsonIgnore
  public Optional<Boolean> getEmbedSubtitles() {
    if (embedSubtitles == null) {
      return Optional.empty();
    }
    return embedSubtitles;
  }

  @JsonIgnore
  public Optional<String> getAudioCodec() {
    if (audioCodec == null) {
      return Optional.empty();
    }
    return audioCodec;
  }

  @JsonIgnore
  public Optional<String> getAudioBitrate() {
    if (audioBitrate == null) {
      return Optional.empty();
    }
    return audioBitrate;
  }

  @JsonIgnore
  public Optional<String> getAudioChannelLayout() {
    if (audioChannelLayout == null) {
      return Optional.empty();
    }
    return audioChannelLayout;
  }

  @JsonIgnore
  public Optional<Integer> getLatency() {
    if (latency == null) {
      return Optional.empty();
    }
    return latency;
  }

  @JsonIgnore
  public Optional<Boolean> getConstantBitrate() {
    if (constantBitrate == null) {
      return Optional.empty();
    }
    return constantBitrate;
  }

  @JsonIgnore
  public Optional<Boolean> getRelayOutput() {
    if (relayOutput == null) {
      return Optional.empty();
    }
    return relayOutput;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("passphrase")
  private Optional<String> _getPassphrase() {
    return passphrase;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("streamid")
  private Optional<String> _getStreamid() {
    return streamid;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("pids")
  private Optional<List<Optional<Integer>>> _getPids() {
    return pids;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("transcode_video")
  private Optional<Boolean> _getTranscodeVideo() {
    return transcodeVideo;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("embed_subtitles")
  private Optional<Boolean> _getEmbedSubtitles() {
    return embedSubtitles;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("audio_codec")
  private Optional<String> _getAudioCodec() {
    return audioCodec;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("audio_bitrate")
  private Optional<String> _getAudioBitrate() {
    return audioBitrate;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("audio_channel_layout")
  private Optional<String> _getAudioChannelLayout() {
    return audioChannelLayout;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("latency")
  private Optional<Integer> _getLatency() {
    return latency;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("constant_bitrate")
  private Optional<Boolean> _getConstantBitrate() {
    return constantBitrate;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("relay_output")
  private Optional<Boolean> _getRelayOutput() {
    return relayOutput;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TargetStream && equalTo((TargetStream) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TargetStream other) {
    return languages.equals(other.languages) && url.equals(other.url) && type == other.type && passphrase.equals(other.passphrase) && streamid.equals(other.streamid) && pids.equals(other.pids) && transcodeVideo.equals(other.transcodeVideo) && embedSubtitles.equals(other.embedSubtitles) && audioCodec.equals(other.audioCodec) && audioBitrate.equals(other.audioBitrate) && audioChannelLayout.equals(other.audioChannelLayout) && latency.equals(other.latency) && constantBitrate.equals(other.constantBitrate) && relayOutput.equals(other.relayOutput);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.languages, this.url, this.type, this.passphrase, this.streamid, this.pids, this.transcodeVideo, this.embedSubtitles, this.audioCodec, this.audioBitrate, this.audioChannelLayout, this.latency, this.constantBitrate, this.relayOutput);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static UrlStage builder() {
    return new Builder();
  }

  public interface UrlStage {
    TypeStage url(@NotNull String url);

    Builder from(TargetStream other);
  }

  public interface TypeStage {
    _FinalStage type(int type);
  }

  public interface _FinalStage {
    TargetStream build();

    _FinalStage languages(List<Integer> languages);

    _FinalStage addLanguages(Integer languages);

    _FinalStage addAllLanguages(List<Integer> languages);

    _FinalStage passphrase(Optional<String> passphrase);

    _FinalStage passphrase(String passphrase);

    _FinalStage passphrase(Nullable<String> passphrase);

    _FinalStage streamid(Optional<String> streamid);

    _FinalStage streamid(String streamid);

    _FinalStage streamid(Nullable<String> streamid);

    _FinalStage pids(Optional<List<Optional<Integer>>> pids);

    _FinalStage pids(List<Optional<Integer>> pids);

    _FinalStage pids(Nullable<List<Optional<Integer>>> pids);

    _FinalStage transcodeVideo(Optional<Boolean> transcodeVideo);

    _FinalStage transcodeVideo(Boolean transcodeVideo);

    _FinalStage transcodeVideo(Nullable<Boolean> transcodeVideo);

    _FinalStage embedSubtitles(Optional<Boolean> embedSubtitles);

    _FinalStage embedSubtitles(Boolean embedSubtitles);

    _FinalStage embedSubtitles(Nullable<Boolean> embedSubtitles);

    _FinalStage audioCodec(Optional<String> audioCodec);

    _FinalStage audioCodec(String audioCodec);

    _FinalStage audioCodec(Nullable<String> audioCodec);

    _FinalStage audioBitrate(Optional<String> audioBitrate);

    _FinalStage audioBitrate(String audioBitrate);

    _FinalStage audioBitrate(Nullable<String> audioBitrate);

    _FinalStage audioChannelLayout(Optional<String> audioChannelLayout);

    _FinalStage audioChannelLayout(String audioChannelLayout);

    _FinalStage audioChannelLayout(Nullable<String> audioChannelLayout);

    _FinalStage latency(Optional<Integer> latency);

    _FinalStage latency(Integer latency);

    _FinalStage latency(Nullable<Integer> latency);

    _FinalStage constantBitrate(Optional<Boolean> constantBitrate);

    _FinalStage constantBitrate(Boolean constantBitrate);

    _FinalStage constantBitrate(Nullable<Boolean> constantBitrate);

    _FinalStage relayOutput(Optional<Boolean> relayOutput);

    _FinalStage relayOutput(Boolean relayOutput);

    _FinalStage relayOutput(Nullable<Boolean> relayOutput);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements UrlStage, TypeStage, _FinalStage {
    private String url;

    private int type;

    private Optional<Boolean> relayOutput = Optional.empty();

    private Optional<Boolean> constantBitrate = Optional.empty();

    private Optional<Integer> latency = Optional.empty();

    private Optional<String> audioChannelLayout = Optional.empty();

    private Optional<String> audioBitrate = Optional.empty();

    private Optional<String> audioCodec = Optional.empty();

    private Optional<Boolean> embedSubtitles = Optional.empty();

    private Optional<Boolean> transcodeVideo = Optional.empty();

    private Optional<List<Optional<Integer>>> pids = Optional.empty();

    private Optional<String> streamid = Optional.empty();

    private Optional<String> passphrase = Optional.empty();

    private List<Integer> languages = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(TargetStream other) {
      languages(other.getLanguages());
      url(other.getUrl());
      type(other.getType());
      passphrase(other.getPassphrase());
      streamid(other.getStreamid());
      pids(other.getPids());
      transcodeVideo(other.getTranscodeVideo());
      embedSubtitles(other.getEmbedSubtitles());
      audioCodec(other.getAudioCodec());
      audioBitrate(other.getAudioBitrate());
      audioChannelLayout(other.getAudioChannelLayout());
      latency(other.getLatency());
      constantBitrate(other.getConstantBitrate());
      relayOutput(other.getRelayOutput());
      return this;
    }

    @java.lang.Override
    @JsonSetter("url")
    public TypeStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("type")
    public _FinalStage type(int type) {
      this.type = type;
      return this;
    }

    @java.lang.Override
    public _FinalStage relayOutput(Nullable<Boolean> relayOutput) {
      if (relayOutput.isNull()) {
        this.relayOutput = null;
      }
      else if (relayOutput.isEmpty()) {
        this.relayOutput = Optional.empty();
      }
      else {
        this.relayOutput = Optional.of(relayOutput.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage relayOutput(Boolean relayOutput) {
      this.relayOutput = Optional.ofNullable(relayOutput);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "relay_output",
        nulls = Nulls.SKIP
    )
    public _FinalStage relayOutput(Optional<Boolean> relayOutput) {
      this.relayOutput = relayOutput;
      return this;
    }

    @java.lang.Override
    public _FinalStage constantBitrate(Nullable<Boolean> constantBitrate) {
      if (constantBitrate.isNull()) {
        this.constantBitrate = null;
      }
      else if (constantBitrate.isEmpty()) {
        this.constantBitrate = Optional.empty();
      }
      else {
        this.constantBitrate = Optional.of(constantBitrate.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage constantBitrate(Boolean constantBitrate) {
      this.constantBitrate = Optional.ofNullable(constantBitrate);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "constant_bitrate",
        nulls = Nulls.SKIP
    )
    public _FinalStage constantBitrate(Optional<Boolean> constantBitrate) {
      this.constantBitrate = constantBitrate;
      return this;
    }

    @java.lang.Override
    public _FinalStage latency(Nullable<Integer> latency) {
      if (latency.isNull()) {
        this.latency = null;
      }
      else if (latency.isEmpty()) {
        this.latency = Optional.empty();
      }
      else {
        this.latency = Optional.of(latency.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage latency(Integer latency) {
      this.latency = Optional.ofNullable(latency);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "latency",
        nulls = Nulls.SKIP
    )
    public _FinalStage latency(Optional<Integer> latency) {
      this.latency = latency;
      return this;
    }

    @java.lang.Override
    public _FinalStage audioChannelLayout(Nullable<String> audioChannelLayout) {
      if (audioChannelLayout.isNull()) {
        this.audioChannelLayout = null;
      }
      else if (audioChannelLayout.isEmpty()) {
        this.audioChannelLayout = Optional.empty();
      }
      else {
        this.audioChannelLayout = Optional.of(audioChannelLayout.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage audioChannelLayout(String audioChannelLayout) {
      this.audioChannelLayout = Optional.ofNullable(audioChannelLayout);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "audio_channel_layout",
        nulls = Nulls.SKIP
    )
    public _FinalStage audioChannelLayout(Optional<String> audioChannelLayout) {
      this.audioChannelLayout = audioChannelLayout;
      return this;
    }

    @java.lang.Override
    public _FinalStage audioBitrate(Nullable<String> audioBitrate) {
      if (audioBitrate.isNull()) {
        this.audioBitrate = null;
      }
      else if (audioBitrate.isEmpty()) {
        this.audioBitrate = Optional.empty();
      }
      else {
        this.audioBitrate = Optional.of(audioBitrate.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage audioBitrate(String audioBitrate) {
      this.audioBitrate = Optional.ofNullable(audioBitrate);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "audio_bitrate",
        nulls = Nulls.SKIP
    )
    public _FinalStage audioBitrate(Optional<String> audioBitrate) {
      this.audioBitrate = audioBitrate;
      return this;
    }

    @java.lang.Override
    public _FinalStage audioCodec(Nullable<String> audioCodec) {
      if (audioCodec.isNull()) {
        this.audioCodec = null;
      }
      else if (audioCodec.isEmpty()) {
        this.audioCodec = Optional.empty();
      }
      else {
        this.audioCodec = Optional.of(audioCodec.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage audioCodec(String audioCodec) {
      this.audioCodec = Optional.ofNullable(audioCodec);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "audio_codec",
        nulls = Nulls.SKIP
    )
    public _FinalStage audioCodec(Optional<String> audioCodec) {
      this.audioCodec = audioCodec;
      return this;
    }

    @java.lang.Override
    public _FinalStage embedSubtitles(Nullable<Boolean> embedSubtitles) {
      if (embedSubtitles.isNull()) {
        this.embedSubtitles = null;
      }
      else if (embedSubtitles.isEmpty()) {
        this.embedSubtitles = Optional.empty();
      }
      else {
        this.embedSubtitles = Optional.of(embedSubtitles.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage embedSubtitles(Boolean embedSubtitles) {
      this.embedSubtitles = Optional.ofNullable(embedSubtitles);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "embed_subtitles",
        nulls = Nulls.SKIP
    )
    public _FinalStage embedSubtitles(Optional<Boolean> embedSubtitles) {
      this.embedSubtitles = embedSubtitles;
      return this;
    }

    @java.lang.Override
    public _FinalStage transcodeVideo(Nullable<Boolean> transcodeVideo) {
      if (transcodeVideo.isNull()) {
        this.transcodeVideo = null;
      }
      else if (transcodeVideo.isEmpty()) {
        this.transcodeVideo = Optional.empty();
      }
      else {
        this.transcodeVideo = Optional.of(transcodeVideo.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage transcodeVideo(Boolean transcodeVideo) {
      this.transcodeVideo = Optional.ofNullable(transcodeVideo);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "transcode_video",
        nulls = Nulls.SKIP
    )
    public _FinalStage transcodeVideo(Optional<Boolean> transcodeVideo) {
      this.transcodeVideo = transcodeVideo;
      return this;
    }

    @java.lang.Override
    public _FinalStage pids(Nullable<List<Optional<Integer>>> pids) {
      if (pids.isNull()) {
        this.pids = null;
      }
      else if (pids.isEmpty()) {
        this.pids = Optional.empty();
      }
      else {
        this.pids = Optional.of(pids.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage pids(List<Optional<Integer>> pids) {
      this.pids = Optional.ofNullable(pids);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "pids",
        nulls = Nulls.SKIP
    )
    public _FinalStage pids(Optional<List<Optional<Integer>>> pids) {
      this.pids = pids;
      return this;
    }

    @java.lang.Override
    public _FinalStage streamid(Nullable<String> streamid) {
      if (streamid.isNull()) {
        this.streamid = null;
      }
      else if (streamid.isEmpty()) {
        this.streamid = Optional.empty();
      }
      else {
        this.streamid = Optional.of(streamid.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage streamid(String streamid) {
      this.streamid = Optional.ofNullable(streamid);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "streamid",
        nulls = Nulls.SKIP
    )
    public _FinalStage streamid(Optional<String> streamid) {
      this.streamid = streamid;
      return this;
    }

    @java.lang.Override
    public _FinalStage passphrase(Nullable<String> passphrase) {
      if (passphrase.isNull()) {
        this.passphrase = null;
      }
      else if (passphrase.isEmpty()) {
        this.passphrase = Optional.empty();
      }
      else {
        this.passphrase = Optional.of(passphrase.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage passphrase(String passphrase) {
      this.passphrase = Optional.ofNullable(passphrase);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "passphrase",
        nulls = Nulls.SKIP
    )
    public _FinalStage passphrase(Optional<String> passphrase) {
      this.passphrase = passphrase;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllLanguages(List<Integer> languages) {
      this.languages.addAll(languages);
      return this;
    }

    @java.lang.Override
    public _FinalStage addLanguages(Integer languages) {
      this.languages.add(languages);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "languages",
        nulls = Nulls.SKIP
    )
    public _FinalStage languages(List<Integer> languages) {
      this.languages.clear();
      this.languages.addAll(languages);
      return this;
    }

    @java.lang.Override
    public TargetStream build() {
      return new TargetStream(languages, url, type, passphrase, streamid, pids, transcodeVideo, embedSubtitles, audioCodec, audioBitrate, audioChannelLayout, latency, constantBitrate, relayOutput, additionalProperties);
    }
  }
}
