/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.Nullable;
import core.NullableNonemptyFilter;
import core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = Voice.Builder.class
)
public final class Voice {
  private final int id;

  private final String voiceName;

  private final Optional<Integer> gender;

  private final Optional<Integer> age;

  private final Optional<Integer> language;

  private final Optional<String> transcript;

  private final Optional<String> description;

  private final Optional<Boolean> isPublished;

  private final Optional<String> signedUrl;

  private final Map<String, Object> additionalProperties;

  private Voice(int id, String voiceName, Optional<Integer> gender, Optional<Integer> age,
      Optional<Integer> language, Optional<String> transcript, Optional<String> description,
      Optional<Boolean> isPublished, Optional<String> signedUrl,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.voiceName = voiceName;
    this.gender = gender;
    this.age = age;
    this.language = language;
    this.transcript = transcript;
    this.description = description;
    this.isPublished = isPublished;
    this.signedUrl = signedUrl;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public int getId() {
    return id;
  }

  @JsonProperty("voice_name")
  public String getVoiceName() {
    return voiceName;
  }

  @JsonIgnore
  public Optional<Integer> getGender() {
    if (gender == null) {
      return Optional.empty();
    }
    return gender;
  }

  @JsonIgnore
  public Optional<Integer> getAge() {
    if (age == null) {
      return Optional.empty();
    }
    return age;
  }

  @JsonIgnore
  public Optional<Integer> getLanguage() {
    if (language == null) {
      return Optional.empty();
    }
    return language;
  }

  @JsonIgnore
  public Optional<String> getTranscript() {
    if (transcript == null) {
      return Optional.empty();
    }
    return transcript;
  }

  @JsonIgnore
  public Optional<String> getDescription() {
    if (description == null) {
      return Optional.empty();
    }
    return description;
  }

  @JsonIgnore
  public Optional<Boolean> getIsPublished() {
    if (isPublished == null) {
      return Optional.empty();
    }
    return isPublished;
  }

  @JsonIgnore
  public Optional<String> getSignedUrl() {
    if (signedUrl == null) {
      return Optional.empty();
    }
    return signedUrl;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("gender")
  private Optional<Integer> _getGender() {
    return gender;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("age")
  private Optional<Integer> _getAge() {
    return age;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("language")
  private Optional<Integer> _getLanguage() {
    return language;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("transcript")
  private Optional<String> _getTranscript() {
    return transcript;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("description")
  private Optional<String> _getDescription() {
    return description;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("is_published")
  private Optional<Boolean> _getIsPublished() {
    return isPublished;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("signed_url")
  private Optional<String> _getSignedUrl() {
    return signedUrl;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof Voice && equalTo((Voice) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(Voice other) {
    return id == other.id && voiceName.equals(other.voiceName) && gender.equals(other.gender) && age.equals(other.age) && language.equals(other.language) && transcript.equals(other.transcript) && description.equals(other.description) && isPublished.equals(other.isPublished) && signedUrl.equals(other.signedUrl);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.voiceName, this.gender, this.age, this.language, this.transcript, this.description, this.isPublished, this.signedUrl);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    VoiceNameStage id(int id);

    Builder from(Voice other);
  }

  public interface VoiceNameStage {
    _FinalStage voiceName(@NotNull String voiceName);
  }

  public interface _FinalStage {
    Voice build();

    _FinalStage gender(Optional<Integer> gender);

    _FinalStage gender(Integer gender);

    _FinalStage gender(Nullable<Integer> gender);

    _FinalStage age(Optional<Integer> age);

    _FinalStage age(Integer age);

    _FinalStage age(Nullable<Integer> age);

    _FinalStage language(Optional<Integer> language);

    _FinalStage language(Integer language);

    _FinalStage language(Nullable<Integer> language);

    _FinalStage transcript(Optional<String> transcript);

    _FinalStage transcript(String transcript);

    _FinalStage transcript(Nullable<String> transcript);

    _FinalStage description(Optional<String> description);

    _FinalStage description(String description);

    _FinalStage description(Nullable<String> description);

    _FinalStage isPublished(Optional<Boolean> isPublished);

    _FinalStage isPublished(Boolean isPublished);

    _FinalStage isPublished(Nullable<Boolean> isPublished);

    _FinalStage signedUrl(Optional<String> signedUrl);

    _FinalStage signedUrl(String signedUrl);

    _FinalStage signedUrl(Nullable<String> signedUrl);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, VoiceNameStage, _FinalStage {
    private int id;

    private String voiceName;

    private Optional<String> signedUrl = Optional.empty();

    private Optional<Boolean> isPublished = Optional.empty();

    private Optional<String> description = Optional.empty();

    private Optional<String> transcript = Optional.empty();

    private Optional<Integer> language = Optional.empty();

    private Optional<Integer> age = Optional.empty();

    private Optional<Integer> gender = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(Voice other) {
      id(other.getId());
      voiceName(other.getVoiceName());
      gender(other.getGender());
      age(other.getAge());
      language(other.getLanguage());
      transcript(other.getTranscript());
      description(other.getDescription());
      isPublished(other.getIsPublished());
      signedUrl(other.getSignedUrl());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public VoiceNameStage id(int id) {
      this.id = id;
      return this;
    }

    @java.lang.Override
    @JsonSetter("voice_name")
    public _FinalStage voiceName(@NotNull String voiceName) {
      this.voiceName = Objects.requireNonNull(voiceName, "voiceName must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage signedUrl(Nullable<String> signedUrl) {
      if (signedUrl.isNull()) {
        this.signedUrl = null;
      }
      else if (signedUrl.isEmpty()) {
        this.signedUrl = Optional.empty();
      }
      else {
        this.signedUrl = Optional.of(signedUrl.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage signedUrl(String signedUrl) {
      this.signedUrl = Optional.ofNullable(signedUrl);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "signed_url",
        nulls = Nulls.SKIP
    )
    public _FinalStage signedUrl(Optional<String> signedUrl) {
      this.signedUrl = signedUrl;
      return this;
    }

    @java.lang.Override
    public _FinalStage isPublished(Nullable<Boolean> isPublished) {
      if (isPublished.isNull()) {
        this.isPublished = null;
      }
      else if (isPublished.isEmpty()) {
        this.isPublished = Optional.empty();
      }
      else {
        this.isPublished = Optional.of(isPublished.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage isPublished(Boolean isPublished) {
      this.isPublished = Optional.ofNullable(isPublished);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "is_published",
        nulls = Nulls.SKIP
    )
    public _FinalStage isPublished(Optional<Boolean> isPublished) {
      this.isPublished = isPublished;
      return this;
    }

    @java.lang.Override
    public _FinalStage description(Nullable<String> description) {
      if (description.isNull()) {
        this.description = null;
      }
      else if (description.isEmpty()) {
        this.description = Optional.empty();
      }
      else {
        this.description = Optional.of(description.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public _FinalStage description(Optional<String> description) {
      this.description = description;
      return this;
    }

    @java.lang.Override
    public _FinalStage transcript(Nullable<String> transcript) {
      if (transcript.isNull()) {
        this.transcript = null;
      }
      else if (transcript.isEmpty()) {
        this.transcript = Optional.empty();
      }
      else {
        this.transcript = Optional.of(transcript.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage transcript(String transcript) {
      this.transcript = Optional.ofNullable(transcript);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "transcript",
        nulls = Nulls.SKIP
    )
    public _FinalStage transcript(Optional<String> transcript) {
      this.transcript = transcript;
      return this;
    }

    @java.lang.Override
    public _FinalStage language(Nullable<Integer> language) {
      if (language.isNull()) {
        this.language = null;
      }
      else if (language.isEmpty()) {
        this.language = Optional.empty();
      }
      else {
        this.language = Optional.of(language.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage language(Integer language) {
      this.language = Optional.ofNullable(language);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "language",
        nulls = Nulls.SKIP
    )
    public _FinalStage language(Optional<Integer> language) {
      this.language = language;
      return this;
    }

    @java.lang.Override
    public _FinalStage age(Nullable<Integer> age) {
      if (age.isNull()) {
        this.age = null;
      }
      else if (age.isEmpty()) {
        this.age = Optional.empty();
      }
      else {
        this.age = Optional.of(age.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage age(Integer age) {
      this.age = Optional.ofNullable(age);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "age",
        nulls = Nulls.SKIP
    )
    public _FinalStage age(Optional<Integer> age) {
      this.age = age;
      return this;
    }

    @java.lang.Override
    public _FinalStage gender(Nullable<Integer> gender) {
      if (gender.isNull()) {
        this.gender = null;
      }
      else if (gender.isEmpty()) {
        this.gender = Optional.empty();
      }
      else {
        this.gender = Optional.of(gender.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage gender(Integer gender) {
      this.gender = Optional.ofNullable(gender);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "gender",
        nulls = Nulls.SKIP
    )
    public _FinalStage gender(Optional<Integer> gender) {
      this.gender = gender;
      return this;
    }

    @java.lang.Override
    public Voice build() {
      return new Voice(id, voiceName, gender, age, language, transcript, description, isPublished, signedUrl, additionalProperties);
    }
  }
}
