/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.texttovoice;

import com.fasterxml.jackson.core.JsonProcessingException;
import core.CambApiApiException;
import core.CambApiException;
import core.ClientOptions;
import core.MediaTypes;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import errors.UnprocessableEntityError;
import java.io.IOException;
import java.lang.Exception;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;
import resources.texttovoice.requests.CreateTextToVoiceRequestPayload;
import resources.texttovoice.requests.GetTextToVoiceResultTextToVoiceResultRunIdGetRequest;
import resources.texttovoice.requests.GetTextToVoiceStatusTextToVoiceTaskIdGetRequest;
import types.GetTextToVoiceResultOut;
import types.HttpValidationError;
import types.OrchestratorPipelineCallResult;
import types.OrchestratorPipelineResult;

public class AsyncTextToVoiceClient {
  protected final ClientOptions clientOptions;

  public AsyncTextToVoiceClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public CompletableFuture<OrchestratorPipelineCallResult> createTextToVoice(
      CreateTextToVoiceRequestPayload request) {
    return createTextToVoice(request,null);
  }

  public CompletableFuture<OrchestratorPipelineCallResult> createTextToVoice(
      CreateTextToVoiceRequestPayload request, RequestOptions requestOptions) {
    HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("text-to-voice")
      .build();
    Map<String, Object> properties = new HashMap<>();
    if (request.getProjectName().isPresent()) {
      properties.put("project_name", request.getProjectName());
    }
    if (request.getProjectDescription().isPresent()) {
      properties.put("project_description", request.getProjectDescription());
    }
    if (request.getFolderId().isPresent()) {
      properties.put("folder_id", request.getFolderId());
    }
    properties.put("text", request.getText());
    properties.put("voice_description", request.getVoiceDescription());
    RequestBody body;
    try {
      body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(properties), MediaTypes.APPLICATION_JSON);
    }
    catch(Exception e) {
      throw new RuntimeException(e);
    }
    Request.Builder _requestBuilder = new Request.Builder()
      .url(httpUrl)
      .method("POST", body)
      .headers(Headers.of(clientOptions.headers(requestOptions)))
      .addHeader("Content-Type", "application/json")
      .addHeader("Accept", "application/json");
    if (request.getTraceparent().isPresent()) {
      _requestBuilder.addHeader("traceparent", request.getTraceparent().get());
    }
    Request okhttpRequest = _requestBuilder.build();
    OkHttpClient client = clientOptions.httpClient();
    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
      client = clientOptions.httpClientWithTimeout(requestOptions);
    }
    CompletableFuture<OrchestratorPipelineCallResult> future = new CompletableFuture<>();
    client.newCall(okhttpRequest).enqueue(new Callback() {
      @Override
      public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
        try (ResponseBody responseBody = response.body()) {
          if (response.isSuccessful()) {
            future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineCallResult.class));
            return;
          }
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          try {
            if (response.code() == 422) {
              future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
              return;
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
          return;
        }
        catch (IOException e) {
          future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
        }
      }

      @Override
      public void onFailure(@NotNull Call call, @NotNull IOException e) {
        future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
      }
    });
    return future;
  }

  public CompletableFuture<OrchestratorPipelineResult> getTextToVoiceStatus(String taskId) {
    return getTextToVoiceStatus(taskId,GetTextToVoiceStatusTextToVoiceTaskIdGetRequest.builder().build());
  }

  public CompletableFuture<OrchestratorPipelineResult> getTextToVoiceStatus(String taskId,
      GetTextToVoiceStatusTextToVoiceTaskIdGetRequest request) {
    return getTextToVoiceStatus(taskId,request,null);
  }

  public CompletableFuture<OrchestratorPipelineResult> getTextToVoiceStatus(String taskId,
      GetTextToVoiceStatusTextToVoiceTaskIdGetRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("text-to-voice")
      .addPathSegment(taskId);if (request.getRunId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json");
      if (request.getTraceparent().isPresent()) {
        _requestBuilder.addHeader("traceparent", request.getTraceparent().get());
      }
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<OrchestratorPipelineResult> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineResult.class));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 422) {
                future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    public CompletableFuture<GetTextToVoiceResultOut> getTextToVoiceResult(
        Optional<Integer> runId) {
      return getTextToVoiceResult(runId,GetTextToVoiceResultTextToVoiceResultRunIdGetRequest.builder().build());
    }

    public CompletableFuture<GetTextToVoiceResultOut> getTextToVoiceResult(Optional<Integer> runId,
        GetTextToVoiceResultTextToVoiceResultRunIdGetRequest request) {
      return getTextToVoiceResult(runId,request,null);
    }

    public CompletableFuture<GetTextToVoiceResultOut> getTextToVoiceResult(Optional<Integer> runId,
        GetTextToVoiceResultTextToVoiceResultRunIdGetRequest request,
        RequestOptions requestOptions) {
      HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("text-to-voice-result");
        if (runId.isPresent()) {
          httpUrl.addPathSegment(runId.get().toString());
        }

        .build();
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl)
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<GetTextToVoiceResultOut> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetTextToVoiceResultOut.class));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 422) {
                future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }
  }
