/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.audioseparation;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.CambApiApiException;
import core.CambApiException;
import core.ClientOptions;
import core.MediaTypes;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import errors.UnprocessableEntityError;
import java.io.File;
import java.io.IOException;
import java.lang.Exception;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;
import java.nio.file.Files;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.MediaType;
import okhttp3.MultipartBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;
import resources.audioseparation.requests.BodyCreateAudioSeparationAudioSeparationPost;
import resources.audioseparation.requests.GetAudioSeparationRunInfoAudioSeparationResultRunIdGetRequest;
import resources.audioseparation.requests.GetAudioSeparationRunsResultsAudioSeparationResultsPostRequest;
import resources.audioseparation.requests.GetAudioSeparationStatusAudioSeparationTaskIdGetRequest;
import types.GetAudioSeparationResultOut;
import types.HttpValidationError;
import types.OrchestratorPipelineCallResult;
import types.OrchestratorPipelineResult;

public class AsyncAudioSeparationClient {
  protected final ClientOptions clientOptions;

  public AsyncAudioSeparationClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public CompletableFuture<OrchestratorPipelineCallResult> createAudioSeparation(
      Optional<File> mediaFile) {
    return createAudioSeparation(mediaFile,BodyCreateAudioSeparationAudioSeparationPost.builder().build());
  }

  public CompletableFuture<OrchestratorPipelineCallResult> createAudioSeparation(
      Optional<File> mediaFile, BodyCreateAudioSeparationAudioSeparationPost request) {
    return createAudioSeparation(mediaFile,request,null);
  }

  public CompletableFuture<OrchestratorPipelineCallResult> createAudioSeparation(
      Optional<File> mediaFile, BodyCreateAudioSeparationAudioSeparationPost request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("audio-separation");if (request.getRunId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
      }
      MultipartBody.Builder body = new MultipartBody.Builder().setType(MultipartBody.FORM);
      try {
        if (mediaFile.isPresent()) {
          String mediaFileMimeType = Files.probeContentType(mediaFile.get().toPath());
          MediaType mediaFileMimeTypeMediaType = mediaFileMimeType != null ? MediaType.parse(mediaFileMimeType) : null;
          body.addFormDataPart("media_file", mediaFile.get().getName(), RequestBody.create(mediaFileMimeTypeMediaType, mediaFile.get()));
        }
        if (request.getProjectName().isPresent()) {
          body.addFormDataPart("project_name", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getProjectName().get()));
        }
        if (request.getProjectDescription().isPresent()) {
          body.addFormDataPart("project_description", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getProjectDescription().get()));
        }
        if (request.getFolderId().isPresent()) {
          body.addFormDataPart("folder_id", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getFolderId().get()));
        }
      }
      catch(Exception e) {
        throw new RuntimeException(e);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body.build())
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      if (request.getTraceparent().isPresent()) {
        _requestBuilder.addHeader("traceparent", request.getTraceparent().get());
      }
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<OrchestratorPipelineCallResult> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineCallResult.class));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 422) {
                future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    public CompletableFuture<OrchestratorPipelineResult> getAudioSeparationStatus(String taskId) {
      return getAudioSeparationStatus(taskId,GetAudioSeparationStatusAudioSeparationTaskIdGetRequest.builder().build());
    }

    public CompletableFuture<OrchestratorPipelineResult> getAudioSeparationStatus(String taskId,
        GetAudioSeparationStatusAudioSeparationTaskIdGetRequest request) {
      return getAudioSeparationStatus(taskId,request,null);
    }

    public CompletableFuture<OrchestratorPipelineResult> getAudioSeparationStatus(String taskId,
        GetAudioSeparationStatusAudioSeparationTaskIdGetRequest request,
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("audio-separation")
        .addPathSegment(taskId);if (request.getRunId().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<OrchestratorPipelineResult> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (response.isSuccessful()) {
                future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), OrchestratorPipelineResult.class));
                return;
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              try {
                if (response.code() == 422) {
                  future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      public CompletableFuture<GetAudioSeparationResultOut> getAudioSeparationRunInfo(
          Optional<Integer> runId) {
        return getAudioSeparationRunInfo(runId,GetAudioSeparationRunInfoAudioSeparationResultRunIdGetRequest.builder().build());
      }

      public CompletableFuture<GetAudioSeparationResultOut> getAudioSeparationRunInfo(
          Optional<Integer> runId,
          GetAudioSeparationRunInfoAudioSeparationResultRunIdGetRequest request) {
        return getAudioSeparationRunInfo(runId,request,null);
      }

      public CompletableFuture<GetAudioSeparationResultOut> getAudioSeparationRunInfo(
          Optional<Integer> runId,
          GetAudioSeparationRunInfoAudioSeparationResultRunIdGetRequest request,
          RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("audio-separation-result");
          if (runId.isPresent()) {
            httpUrl.addPathSegment(runId.get().toString());
          }

          .build();
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl)
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<GetAudioSeparationResultOut> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (response.isSuccessful()) {
                future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetAudioSeparationResultOut.class));
                return;
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              try {
                if (response.code() == 422) {
                  future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      public CompletableFuture<Map<String, GetAudioSeparationResultOut>> getAudioSeparationRunsResults(
          GetAudioSeparationRunsResultsAudioSeparationResultsPostRequest request) {
        return getAudioSeparationRunsResults(request,null);
      }

      public CompletableFuture<Map<String, GetAudioSeparationResultOut>> getAudioSeparationRunsResults(
          GetAudioSeparationRunsResultsAudioSeparationResultsPostRequest request,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("audio-separation-results");if (request.getRunId().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "run_id", request.getRunId().get().toString(), false);
          }
          RequestBody body;
          try {
            body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
          }
          catch(Exception e) {
            throw new RuntimeException(e);
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("POST", body)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json");
          if (request.getTraceparent().isPresent()) {
            _requestBuilder.addHeader("traceparent", request.getTraceparent().get());
          }
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<Map<String, GetAudioSeparationResultOut>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                if (response.isSuccessful()) {
                  future.complete(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<Map<String, GetAudioSeparationResultOut>>() {}));
                  return;
                }
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                try {
                  if (response.code() == 422) {
                    future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HttpValidationError.class)));
                    return;
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                future.completeExceptionally(new CambApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class)));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new CambApiException("Network error executing HTTP request", e));
            }
          });
          return future;
        }
      }
